### ISSUE TITLE
Kamera mit Doorbell kombinieren

### ISSUE THREAD

**Issue by rauchmandl** [rdmtc/RedMatic-HomeKit#125]
Hallo erstmal,

habe ein geschlossenes "issue" #30 gefunden:

ist mit dem "universal doorbell accessory" so etwas wie das gemeint?:
https://github.com/thkl/homebridge-homematic/wiki/Video-DoorBell

Denn das habe ich "noch" im Einsatz. 
Läuft bei mir mit einer "HikVision DomeCamera" perfekt. 
Mittlerweile der einzige Grund für meinen 2ten Raspi mit homebridge. Der Rest läuft perfekt unter RedMatic(Danke nochmal).

Kann ich das unter RedMatic nachbauen? Wäre für Tips sehr dankbar, da ich Anfänger bin.

Danke und LG, Josef

**Comment by hobbyquaker** [comment]
Muss ich mir nochmal anschauen. Bin mir nicht sicher ob es reicht einen Doorbell Service einfach in den gleichen Raum wie Kamera zu packen (dann wäre es bereits möglich mit dem Universal Accessory) oder ob es notwendig ist dass die Doorbell als weiterer Service mit ins Kamera Accessory gepackt werden muss (dann müsste ich das Kamera-Accessory noch erweitern).

**Comment by rauchmandl** [comment]
Falls es hilft:
Ich hab dafür folgende HM-Geräte im Einsatz:
Türklingel mit HM-PBI-4-FM
Türöffner mit HM-LC-Sw4-DR
Bewegungsmelder mit HM-Sen-MDIR-O-2
und eben die besagte "HikVision" IP Kamera, die perfekt mit deinem Kamera Accessory arbeitet.

**Comment by spiu16** [comment]
@rauchmandl 

> und eben die besagte "HikVision" IP Kamera, die perfekt mit deinem Kamera Accessory arbeitet.

ist mit "Kamera Accessory" das Universal Accessory gemeint?
Danke!

**Comment by rauchmandl** [comment]
@spiu16 

nein, damit ist der node "camera" unter "redmatic homekit" gemeint. Sry falls ich mich falsch ausgedrückt habe, wie gesagt, ich bin Anfänger und die Fachbegriffe happern no a bisi :-)
Hab da auch keinen flow den ich posten könnte, habe den node reingezogen und konfiguriert. Klappte auf Anhieb.

**Comment by spiu16** [comment]
Ah, okay, das hatte ich noch nicht gesehen.
Danke

**Comment by spiu16** [comment]
@hobbyquaker Gibt es für das Camera Device eine Dokumentation?

**Comment by hobbyquaker** [comment]
Noch nicht (#100). Aber im Endeffekt sind alle Konfigurationsoptionen und Beispielkonfigs hier dokumentiert: 
* https://github.com/KhaosT/homebridge-camera-ffmpeg
* https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki

**Comment by spiu16** [comment]
Ok Danke, das hilft mir schon mal.
Vielleicht könnte man in der Hilfe für den Camera Node auf diese Links verweisen?

**Comment by rauchmandl** [comment]
@hobbyquaker 

Beim Camera Node ist mir aufgefallen, dass sich das Bild nicht aktualisiert. Erst wenn ich es anklicke wird der Livestream gestartet. Bei meiner homebridge-Lösung aktualisierte sich das Bild alle paar Sekunden. Kann ich das irgendwie einstellen oder beeinflußen?

LG, Josef

**Comment by hobbyquaker** [comment]
was hast Du denn als "Stillimage Source" eingetragen? da müsste sowas wie `-i http://...` drinstehen. Bekommst Du denn ein Bild wenn Du diese Url im Webbrowser aufrufst?

**Comment by rauchmandl** [comment]
Hallo, habe das -i nicht vorne dran... aber im browser habe ich damit sofort ein Bild.
Unter homebridge habe ich gar nichts eingetragen bei der Stillimage Source. Hat sich trotzdem aktualisiert. Ich versuchs mal mit dem -i.

**Comment by rauchmandl** [comment]
das -i wars... vielen lieben Dank!!! aktualisiert sich jetzt perfekt alle 10 Sekunden.

Vielen Dank
LG, Josef

**Comment by hobbyquaker** [comment]
@rauchmandl hab das nochmal alles durchgetestet. Wenn Du ein Doorbell oder MotionDetector Accessory in den gleichen Raum packst wie die Kamera sollte das bereits funktionieren, ich bekomme dann eine Push-Nachricht mit einem Snapshot der Kamera.

**Comment by rauchmandl** [comment]
@hobbyquaker hab das gerade versucht und was soll ich sagen, funktioniert einwandfrei. Hätte nicht gedacht, dass das so einfach ist. Nur den Türöffner hab ich noch nicht integriert bekommen, hast du eine Idee wie ich den unterbringe? 

Vielen Dank, LG Josef

**Comment by hobbyquaker** [comment]
Ich vermute da muss nur ein Door Accessory in den gleichen Raum. Ich teste es asap mal.

**Comment by rauchmandl** [comment]
Mit door Accessory ist das Universal Accessory "Door" gemeint? wenn ja, dann funktioniert es so nicht! LG Josef

**Comment by Boarder** [comment]
Wäre klasse wenn jemand von euch der so einen Doorbell schon mal eingerichtet hat kurz schreiben könnte wir das geht. 👍
Ich würde gerne wenn jemand klingelt ein Bild geschickt bekommen. 
Cam ist eingerichtet und läuft. 1000 Dank

**Comment by KPfundstein** [comment]
Hallo Ich habe sowohl einen motion detector, eine doorbell und die Kamera im gleichen Raum, leider erhalte ich bei den PUSH Nachrichten keine Vorschau :-( hat das jemand gelöst ?

**Comment by KPfundstein** [comment]
ich habe jetzt noch etwas im www gesucht und es scheint tatsächlich mit IOS13 nicht mehr zu funktionieren. Besteht die Möglichkeit eine Video Door Bell zu implementieren ? habe leider nichts gefunden ....

**Comment by hobbyquaker** [comment]
@KPfundstein Doorbell ist nun implementiert, Hinweise siehe https://github.com/rdmtc/RedMatic-HomeKit/issues/198#issuecomment-570273593
