### ISSUE TITLE
Heizungsgruppen

### ISSUE THREAD

**Issue by hobbyquaker** [rdmtc/RedMatic-HomeKit#131]

**Comment by hobbyquaker** [comment]
@ptweety In RedMatic 4.2.0 steckt nun support für die Heizungsgruppen. Bitte gib Bescheid ob alles funktioniert wie es soll.

**Comment by ptweety** [comment]
Zumindest für HmIP-Heating kann ich das nach einem kurzen Test bestätigen. Vielen Dank für die Implementierung.
