### ISSUE TITLE
Wandthermostate ohne Batterie

### ISSUE THREAD

**Issue by udochrist** [rdmtc/RedMatic-HomeKit#133]
Meine HM-BWTH Wandthermostate (die -WTH meines Wissens auch) sind direkt mit strom verbunden und nutzen keine batterie. im HomeKit werden die trotzdem mit batterie (ungeladen) dargestellt. das führt zu Batterie-ist-leer Fehlern bei z.b. eve.

für diese geräte sollte die batterie-characteristic entfernt werden.

**Comment by udochrist** [comment]
Nochmal nachgeguckt: die hmip-wth und -wth2 sind mit Batterie, die hmip-Bwth und hmip-bwth24 sind ohne Batterie. Für die letzten beiden sollte die characteristic raus.

**Comment by hobbyquaker** [comment]
Wird erledigt. Allerdings kam mir jetzt noch was: #134

**Comment by spiu16** [comment]
Nochmal dazu: nach Update auf RedMatic 4.0.1 wird bei meinen HmIP-BWTH immer noch "Batteriestatus 0%" und "Batterie wird geladen: Nein" angezeigt.

**Comment by udochrist** [comment]
ja. in der 4.0.1 zeigen die geräte noch die Batterie. muss man was spezielles nach dem install/neustart durchführen damit die weg sind?

**Comment by hobbyquaker** [comment]
Ich hatte in 4.0.0 und 4.0.1 leider Bugs fabriziert die dazu führten das bereits installierte Nodes mit Binärpaketen (was u.A. auch RedMatic-HomeKit ist) nicht aktualisiert wurden. Entweder auf RedMatic 4.0.2 gehen oder im RedMatic UI unter "Packages" einmal RedMatic-HomeKit deinstallieren und neuinstallieren, dann Node-RED Restart.
