### ISSUE TITLE
Keine Verbindung zum iPhone möglich

### ISSUE THREAD

**Issue by chuenniger** [rdmtc/RedMatic-HomeKit#136]
Hallo,

erstmal Danke für euren support und eure Mühen.

Ich habe versucht, dies einzurichten und beim Schritt `Bei einer erfolgreich aktivierten Bridge wird in dem Bridge Konfigurationsdialog nun ein QR-Code angezeigt`. 

Also scanne ich den QR-Code und es kommt folgende Meldung im *iPhone XS* (Code habe ich verfälscht)

![IMG_1551](https://user-images.githubusercontent.com/188438/55227226-30534600-5217-11e9-958e-2ea2706b1b83.jpeg)

Ich habe die Bridge nun 3 mal gelöscht und neu angelegt und probiert.

Jemand eine zündende Idee?

Gruß
hu3nn1

**Comment by hobbyquaker** [comment]
Steht dem eventuell die CCU Firewall im Weg? Stell sie mal testweise auf "Ports Offen" (falls sie das noch nicht ist).

**Comment by chuenniger** [comment]
Oh man, das war es. Ich danke Dir, Ticket kann geschlossen werden :)
