### ISSUE TITLE
Heizungsgruppen (Sec-Sco + CC-RT-DN) melden "keine Antwort"

### ISSUE THREAD

**Issue by udochrist** [rdmtc/RedMatic-HomeKit#138]
Seit der letzten Version werden auch die Heizungsgruppen nach homekit importiert.
Ich nutze 5 verschiedene Gruppen für Heizungen. 4 sind Sec-Sco + CC-RT-DN + TC-IT-WM-W-EU in jeweils verschiedenen Mengen und eine mit CC-RT-DN + Sec-Sco.
Nur diese letzte Gruppe meldet "Keine Meldung". Die anderen funktionieren.

**Comment by hobbyquaker** [comment]
Könntest Du mir dafür ein Log auf Debug Level zukommen lassen? (hobbyquaker@gmail.com wenn du es nicht hier posten möchtest)

**Comment by udochrist** [comment]
> Könntest Du mir dafür ein Log auf Debug Level zukommen lassen? ([hobbyquaker@gmail.com](mailto:hobbyquaker@gmail.com) wenn du es nicht hier posten möchtest)

Schicke ich. Was soll ich machen? nur im Debug starten und warten bis die home,app antworten meldet auf geräten?

**Comment by udochrist** [comment]
Interessant. ich habe gerade zwei gruppen aus HMip (BWTH + fensterkontakt) erstellt. beide wurden importiert und gehen, die andere aber immer noch nicht.

**Comment by hobbyquaker** [comment]
Jap, Loglevel Debug setzen, Node-RED neustarten, minute warten, einmal Home App öffnen, das sollte reichen.

**Comment by hobbyquaker** [comment]
Das gehts um die Gruppe `VirtualDevices.INT0000008 Living Area.Group.Heating` - richtig? Ich hab schon eine Vermutung was ich da nicht bedacht hab... Fix kommt asap.

**Comment by udochrist** [comment]
nein. :-) es ist die entrance. ich teste gerade mit 4.3.0

**Comment by udochrist** [comment]
Geht mit 4.3.0 auch nicht...

![Bildschirmfoto 2019-04-18 um 22 38 10](https://user-images.githubusercontent.com/869637/56389765-b10bcd80-622a-11e9-9e2c-ec2aef5a766e.png)

**Comment by hobbyquaker** [comment]
hmm... Das macht mich jetzt erstmal etwas ratlos :-) Im log finde ich kein Eintrag `addAccessory INT0000` zu der Entrance.Group - aber das Accessory ist ja trotzdem offensichtlich da. Welche `INT0000...` Adresse hat diese Gruppe?

**Comment by udochrist** [comment]
ist die Entrance.Group.Heating INT0000005. ich lösche die mal und teste nochmal. evtl ist ja was auf der ccu verklemmt...

**Comment by udochrist** [comment]
gelöscht, neu angelegt. Die Gruppe will nicht. Alle anderen gehen.

**Comment by hobbyquaker** [comment]
Ne, ich glaub ich weiss was da passiert: der Node wirft wohl eine Exception bei der INT0000005 - und zwar bevor überhaupt irgendwas geloggt wird. Leider ist Node-RED was die Behandlung und das Loggen von Exceptions angeht etwas seltsam, die sind u.U. im Log einfach unsichtbar, ich glaube das ist hier der Fall. Ich versuch das mal nachzustellen, muss eigentlich "nur" den Wandthermostat aus einer meiner Gruppen mal rausnehmen, gib mir etwas Zeit.

**Comment by hobbyquaker** [comment]
Eine Sache würde mir noch helfen... Kannst Du mir mal den Inhalt der Datei `/etc/config/groups.gson` zukommen lassen?

**Comment by hobbyquaker** [comment]
Kannst Du mal bitte in der homekit-homematic Konfiguration den HumiditySensor für diese Gruppe deaktivieren, Deployen, Node-RED neustarten und dann nochmal schauen ob sich was ändert?

**Comment by udochrist** [comment]
gemacht. sensor ist verschwunden. leider aber noch "Keine Antwort"

**Comment by hobbyquaker** [comment]
ich hoffe ich habs fixen können, könntest Du mal diese Datei https://raw.githubusercontent.com/rdmtc/RedMatic-HomeKit/master/homematic-devices/hm-cc-vg-1.js runterladen und nach `/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/` kopieren - Node-RED Neustarten und checken ob der Fehler damit aus der Welt ist?

**Comment by udochrist** [comment]
```
# cd /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devi
ces/
# ll hm-cc-vg-1.js 
-rw-rw-r--    1 root     root          8919 Apr 18 23:24 hm-cc-vg-1.js
# 
```

aber immer noch keine Antwort nach dem durchstarten

**Comment by hobbyquaker** [comment]
hmm schade, zu optimistisch gewesen ;-) Dann muss ich dich um Geduld bitten, schaffe es heute wohl nichtmehr.

**Comment by hobbyquaker** [comment]
>  ich hab aber keinen humidity sensor mehr obwohl ich ihn wieder angeschaltet hatte

Das ist Absicht, ich lege den Service jetzt nur noch an wenn es auch ein Humidity-Datenpunkt gibt - und den haben ja nur die Wandthermostate, die Heizungssteller nicht.

**Comment by udochrist** [comment]
kein stress... das kann warten

**Comment by udochrist** [comment]
> > ich hab aber keinen humidity sensor mehr obwohl ich ihn wieder angeschaltet hatte
> 
> Das ist Absicht, ich lege den Service jetzt nur noch an wenn es auch ein Humidity-Datenpunkt gibt - und den haben ja nur die Wandthermostate, die Heizungssteller nicht.

ok. dann sollte er aber in der gerate-konfig weg. nicht nur im HomeKit. das hat mich verwirrt...

**Comment by hobbyquaker** [comment]
> ok. dann sollte er aber in der gerate-konfig weg. nicht nur im HomeKit. das hat mich verwirrt...

Geb ich Dir recht, kommt auf die Todo.

**Comment by hobbyquaker** [comment]
@udochrist Kannst Du mal checken ob die Gruppe mit RedMatic 4.3.1 jetzt funktioniert?

**Comment by udochrist** [comment]
Ja. Funktioniert jetzt. sehr gut.
