### ISSUE TITLE
Implement HmIP-WRC6

### ISSUE THREAD

**Issue by frankheit** [rdmtc/RedMatic-HomeKit#139]
Wäre es evtl. möglich den HmIP 6-fach Taster (HmIP-WRC6) als Schalter in HomeKit abzubilden bzw. ihn verfügbar zu machen?

**Comment by hobbyquaker** [comment]
siehe https://github.com/rdmtc/RedMatic/wiki/Homekit#tasten und https://homematic-forum.de/forum/viewtopic.php?t=47043

**Comment by frankheit** [comment]
Okay, werde ich testen!
Danke.

**Comment by fabsewup** [comment]
Leider empfange ich keine Events in Redmatic. Weder als Value mit Dummyprogramm, richtigen Programm, oder auch Homematic Manager "reportValueUsage".

Mittels Programm auf der CCU funktioniert der WRC6 einwandfrei.

Ich habe es auch über das rpc Event probiert. Auch hier bekomme ich über keinen der 6 Kanäle ein Event.

Im Debug wird keinerlei Reaktion angezeit.

Hat hier jemand noch eine Idee woran dies liegen könnte?
