### ISSUE TITLE
HomeKit für CCU3: Batterien leer bei allen Heizungsgruppen und der Wetterstation Plus

### ISSUE THREAD

**Issue by superpower10** [rdmtc/RedMatic-HomeKit#143]
Alle mein Homematic IP Heizungsgruppen zeigen, dass der Boost Schalter 0% Batterie hat (HmIP-eTRV and HmIP-eTRV-2).

Auch meine Wetterstation Plus (HmIP-SWO-PL) zeigt 0% Batterie an.

Aber alle Batterien sind voll.

**Comment by hobbyquaker** [comment]
Sollte mit RedMatic 4.4.1 gefixt sein, bitte gib Bescheid ob es passt.

**Comment by superpower10** [comment]
Vielen Dank!

Bei den Heizungsgruppen passt es jetzt.

Bei der Wetterstation Plus (HmIP-SWO-PL) leider noch nicht.

**Comment by hobbyquaker** [comment]
Hmm, da bräucht ich mal Deine Hilfe. Könntest Du Dir den Homematic-Manager installieren, dann im Tab Geräte mit dem Plus in der Spalte ganz Links das Gerät (also die Wetterstation) aufklappen und dann im Kanal :0 auf den "Values" Button drücken. Von dem Dialog der dann aufgeht bräucht ich mal ein Screenshot.

**Comment by superpower10** [comment]
Hier der Screenshot:

<img width="964" alt="Bildschirmfoto 2019-05-08 um 17 09 07" src="https://user-images.githubusercontent.com/20533966/57386138-101e8b80-71b4-11e9-9a2c-fbd6b904eb9a.png">

**Comment by hobbyquaker** [comment]
Hmm, strange. `OPERATING_VOLTAGE` ist 0. Dann ist mir jetzt klar warum dass ne Batterie-Leer Warnung wirft ;-) Scheinbar wird dieser Datenpunkt bei diesem Gerät nicht befüllt, warum auch immer... Werde ihn im nächsten Release ignorieren und BatteryLevel je nach `LOW_BAT` auf 0% bzw. 100% setzen.

**Comment by hobbyquaker** [comment]
@superpower10 Gib bitte Bescheid ob es jetzt passt. (RedMatic >= 4.4.2)

**Comment by superpower10** [comment]
So, nachdem ich jetzt alles mit einem alten Backup neu aufgesetzt, neueste RedMatic und RedMatic-HomeKit installiert habe, kann ich sagen, dass es jetzt funktioniert.

Vielen Dank!
