### ISSUE TITLE
HomeKit mit CCU: Zeige Regen als Bewegung

### ISSUE THREAD

**Issue by superpower10** [rdmtc/RedMatic-HomeKit#144]
Über Homebridge wird Regen als Bewegung in HomeKit angezeigt. Über RedMatic HomeKit leider nicht.

Wäre schon, wenn dass (ohne eigenen Flow) drin wäre:

![IMG_1355](https://user-images.githubusercontent.com/20533966/57184643-a43fd880-6ebe-11e9-8766-267cada77585.jpg)

**Comment by hobbyquaker** [comment]
Das fehlt noch da es keine offizielle Apple Characteristic ist (wird auch weder von der Home.app noch von Siri unterstützt). Habe es allerdings schon auf der Todo in Zukunft auch Elgato Characteristiken zu untersützen: https://github.com/rdmtc/RedMatic-HomeKit/issues/114

**Comment by superpower10** [comment]
Ich bin gerade dabei dies selbst als Flow zu realisieren.

Leider funktioniert das nicht, könnte mir hierbei jemand helfen?

```[{"id":"a56e2a5d.251af","type":"redmatic-homekit-universal","z":"aeb8703c.8ef4b8","bridgeConfig":"df7bbdd.1c6d8c","name":"RegenAlsBewegung","services":[{"subtype":"0","service":"MotionSensor","name":"Regen"}],"x":400,"y":240,"wires":[["c472eb97.da9ee"]]},{"id":"50abff38.5388b8","type":"ccu-rpc-event","z":"aeb8703c.8ef4b8","name":"Regen","iface":"HmIP-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"","functionsRx":"str","device":"001818A992BC92","deviceRx":"str","deviceName":"","deviceNameRx":"str","deviceType":"","deviceTypeRx":"str","channel":"001818A992BC92:1","channelRx":"str","channelName":"","channelNameRx":"str","channelType":"","channelTypeRx":"str","channelIndex":"","channelIndexRx":"str","datapoint":"RAINING","datapointRx":"str","change":false,"working":false,"cache":true,"topic":"${CCU}/${Interface}/${channelName}/${datapoint}","x":150,"y":180,"wires":[["a56e2a5d.251af","c472eb97.da9ee"]]},{"id":"c472eb97.da9ee","type":"debug","z":"aeb8703c.8ef4b8","name":"Es regnet","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":400,"y":160,"wires":[]},{"id":"df7bbdd.1c6d8c","type":"redmatic-homekit-bridge","z":"","name":"RedMatic Bridge","username":"CC:22:3D:FB:81:EB","pincode":"484-84-791","port":"51826"},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":""}]```


<img width="476" alt="Bildschirmfoto 2019-05-08 um 17 20 19" src="https://user-images.githubusercontent.com/20533966/57387249-4230ed00-71b6-11e9-9a7b-14a36b64ef92.png">
<img width="471" alt="Bildschirmfoto 2019-05-08 um 17 20 39" src="https://user-images.githubusercontent.com/20533966/57387260-48bf6480-71b6-11e9-8d87-ea3eacdf8a02.png">
<img width="465" alt="Bildschirmfoto 2019-05-08 um 17 20 44" src="https://user-images.githubusercontent.com/20533966/57387283-55dc5380-71b6-11e9-8aad-521419151620.png">
<img width="476" alt="Bildschirmfoto 2019-05-08 um 17 20 54" src="https://user-images.githubusercontent.com/20533966/57387309-5ffe5200-71b6-11e9-8b51-f16d2df39728.png">
<img width="310" alt="Bildschirmfoto 2019-05-08 um 17 21 02" src="https://user-images.githubusercontent.com/20533966/57387321-668cc980-71b6-11e9-9d50-19cab3a18e76.png">

**Comment by hobbyquaker** [comment]
Wenn Dein Ziel die Anzeige in der Elgato App ist das so nicht machbar, ich glaube nicht dass Elgato für den Regen den MotionSensor Service nutzt, ich glaube eher das steckt in der `WeatherCondition` Characteristic (https://github.com/ebaauw/homebridge-lib/blob/master/lib/EveHomeKitTypes.js#L209) die aber wie gesagt keine offizielle Apple Characteristic ist und _noch_ nicht von RedMatic-HomeKit unterstüzt wird.

**Comment by hobbyquaker** [comment]
Crosspost: https://homematic-forum.de/forum/viewtopic.php?p=507935#p507935

**Comment by superpower10** [comment]
Das hat nichts mit Elgato App (heute Eve).

Das wird als ganz normaler Bewegungssensor angezeigt. Hier die Anzeige aus der Apple Home App:

![IMG_1368](https://user-images.githubusercontent.com/20533966/57402689-23dbe900-71d8-11e9-8fa5-e28fff4f6b77.jpg)

Ich will das einfach nachbauen. 

PS: Sorry wg. dem Crossposting

**Comment by hobbyquaker** [comment]
Ah ok, verstehe. Da müsstest Wenn Du ein MotionSensor Service angelegt hast eine Nachricht mit Topic `0/MotionDetected` (boolean `true`/`false`) reinschicken, dann sollte das gehen.

**Comment by superpower10** [comment]
Das mache ich. Es geht aber leider nicht. Deshalb habe ich hier und im Forum um Hilfe gebeten.

**Comment by hobbyquaker** [comment]
```
[{"id":"e74fcc14.9a497","type":"redmatic-homekit-universal","z":"4cd19d23.157164","bridgeConfig":"f001efc.9496b1","name":"Test-BWM","services":[{"subtype":"0","service":"MotionSensor","name":"Test-BWM"}],"x":530,"y":260,"wires":[[]]},{"id":"9cd5a06e.fa73b","type":"inject","z":"4cd19d23.157164","name":"","topic":"0/MotionDetected","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":280,"y":220,"wires":[["e74fcc14.9a497"]]},{"id":"a26c392.e8215c8","type":"inject","z":"4cd19d23.157164","name":"","topic":"0/MotionDetected","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":280,"y":280,"wires":[["e74fcc14.9a497"]]},{"id":"f001efc.9496b1","type":"redmatic-homekit-bridge","z":"","name":"Test Bridge","username":"CC:22:3D:67:54:43","pincode":"851-64-721","port":"51826"}]
```

**Comment by hobbyquaker** [comment]
Eben getestet, funktioniert. Sollte diese Log-Meldungen erzeugen wenn man erst den oberen dann den unteren Inject Node anklickt:

```
May  9 20:47:31 homematic-raspi daemon.debug node-red[7169]: [redmatic-homekit-universal:Test-BWM] -> hap 0/MotionDetected true
May  9 20:47:31 homematic-raspi daemon.debug node-red[7169]: [redmatic-homekit-universal:Test-BWM] hap -> 0/MotionDetected true
May  9 20:47:32 homematic-raspi daemon.debug node-red[7169]: [redmatic-homekit-universal:Test-BWM] -> hap 0/MotionDetected false
May  9 20:47:32 homematic-raspi daemon.debug node-red[7169]: [redmatic-homekit-universal:Test-BWM] hap -> 0/MotionDetected false


```

**Comment by superpower10** [comment]
Das funktioniert, aber meines funktioniert nicht.

Es kommt laut Debug Boolean.true und Boolean.false raus (siehe oben), aber der Universal (Motion - siehe oben) geht nicht. Es kommt eine Fehlermeldung:

<img width="330" alt="Bildschirmfoto 2019-05-09 um 21 53 48" src="https://user-images.githubusercontent.com/20533966/57482462-f8730000-72a4-11e9-9e88-986dde5db35f.png">

**Comment by superpower10** [comment]
Habe es hinbekommen.

Hiermit:
<img width="506" alt="Bildschirmfoto 2019-05-10 um 00 06 01" src="https://user-images.githubusercontent.com/20533966/57489797-76400700-72b7-11e9-8d74-616d31dee95b.png">
