### ISSUE TITLE
Homekit Keine Antwort

### ISSUE THREAD

**Issue by OliverGreenforest** [rdmtc/RedMatic-HomeKit#148]
Erstmals vielen Dank für die Mühen. 
Arbeite auf einer CCU 3 (firmware 3.45.7), Redmatic 4.7.l. Nachdem die Redmatic-Geräte auf Homekit (neueste IOS, TVOS, MOJAVE Version auf allen Clients) alle nicht mehr ansprechbar waren ("Keine Antwort" ) habe ich geupdated auf die o.a. Versionen. Danach ließen sich die Geräte wieder in HK steuern mit einer neu angelegten Redmatic-Bridge in Homekit (danach 2 h Arbeit, um alle Aktoren, SVs etc. wieder richtig in Homekit einzurichten.) 
Heute morgen zeigen auf einen Schlag alle Geräte wieder "Keine Antwort". Egal, ob Neustart Redmatic oder CCU3, ich bekomme sie nicht responding in Homekit und befürchte, die zahlreichen Variablen, Programme und Aktoren wieder von vorne mit einer neuen RM-Bridge einrichten zu müssen. Kann man mir weiterhelfen? Vielen Dank!

**Comment by hobbyquaker** [comment]
Da müsstest mal ein Log auf Level Debug zeigen.
