### ISSUE TITLE
Question: What is used by RedMatic-HomeKit to support Apple Bonjour for HomeKit?

### ISSUE THREAD

**Issue by djiwondee** [rdmtc/RedMatic-HomeKit#150]
Hello,

there are a few implementations of available for Node-red to support HomeKit on Linux based environments. What is used by Redmatic-HomeKit to connect to Apple HomeKit HAP-services? Is it `libavahi` e. g. [this](https://packages.debian.org/de/jessie/libavahi-compat-libdnssd-dev) for Debian?

**Comment by hobbyquaker** [comment]
There is no dependency to Avahi, HAP-Nodejs switched to a pure js mDNS implementation a while ago.
