### ISSUE TITLE
HomeKit: Virtuelle Kanäle nutzbar machen

### ISSUE THREAD

**Issue by CharlyFive** [rdmtc/RedMatic-HomeKit#157]
Hallo, 

ich weiß nicht genau welcher Kanal die Erweiterungen für HomeKit am Dimmer HmIP-BDT nimmt, aber ich würde gerne einen anderen Kanal wählen können, den Kanal 5.

Grund: Bei mir ist der Präsenzmelder mit dem HmIP-BDT an Kanal 5 verknüpft. Wenn der Präsenzmelder das Licht also an Kanal 5 einschaltet, dann bekomme ich das Licht mit Siri erstmal nicht geschaltet weil Siri das Licht am "falschen" Kanal schaltet.

Wäre es möglich in einer nächsten Version die Kanäle bei den HmIP-BDT auswählen zu können?

Danke!

**Comment by hobbyquaker** [comment]
Todo:
- [ ] HmIP-BDT
- [ ] HmIP-BROLL
- [ ] HmIP-BBL
- [ ] HmIP-BDT
- [ ] HmIP-PDT
- [ ] HmIP-BSL
- [ ] HmIPW-DRS4
- [ ] HmIP-PS
- [ ] HmIP-PSM
- [ ] HmIP-FSM
- [ ] HmIP-BSM
- [ ] HmIP-PCBS
- [ ] HmIP-PCBS2
- [ ] HmIP-PCBS-BAT
- [ ] HM-LC-Dim1L-CV
- [ ] HM-LC-Dim2L-SM

**Comment by LevelOne2k** [comment]
@hobbyquaker Wann kann man mit dem Release rechnen?

**Comment by Macem79** [comment]
Würde mich auch interessieren @hobbyquaker

**Comment by CharlyFive** [comment]
Passier denn hier noch was? @hobbyquaker

**Comment by CharlyFive** [comment]
@hobbyquaker ich will echt nicht drängeln oder so, aber wann kann man denn nun mal mit der Erweiterung rechnen? Ich habe diesen Wunsch vor knapp 3 Monaten geäußert, und bisher ist noch nicht wirklich etwas passiert, zumindest nicht offensichtlich. Ich bin ja auch scheinbar, wie ich den paar letzten Kommentaren hier entnehme, nicht der einzige der diese Erweiterung haben möchte.

Zumindest wäre ein Kommentar deinerseits angebracht. Bisher ist dies hier seit fast einem Monat von dir Kommentarlos zurückgeblieben.

Danke!

**Comment by hobbyquaker** [comment]
„it‘s done when it‘s done“
ich mach grade ne sommerpause, ich schätz mal august/september/oktober. Wem das zu lange dauert kann ich nicht helfen, oder willst Dein Geld zurück? ;-)

**Comment by Macem79** [comment]
Geil, dass nennt man support, NICHT! *thumbs down*

**Comment by CharlyFive** [comment]
@Macem79 Jau, absolut lächerlich. Werde mich hier verabschieden. Solch ein eingebildetes getue hier brauche ich nicht @hobbyquaker

**Comment by hobbyquaker** [comment]
*Kopfschüttel
Ich glaube ihr begreift nicht dass das ein Hobbyprojekt ist das ich in meiner (nicht unbegrenzt verfügbaren) Freizeit stemme und ohne irgendeine Gegenleistung zu fordern zur Verfügung stelle. Hier eine solche Anspruchshaltung an den Tag zu legen ist in meinen Augen schlichtweg eine Unverschämtheit. Ich bin euch gar nichts schuldig.
Dass ich auf solche "wann ists denn endlich fertig" Nachfragen nicht oder schnippisch reagiere halte ich übrigens auch nicht für "eingebildetes Getue" sondern für die einzig sinnvolle Reaktion - um den eben ausgeführten Sachverhalt auch solchen Leuten unmissverständlich klarzumachen die offensichtlich öfter mal Pech beim Denken haben.
Zu guter letzt: ich habe mich bereit erklärt dieses Feature zu implementieren, wenn man ein Blick in die Commit History wirft sieht man dass ich auch bereits damit angefangen habe, das ist nicht wenig Arbeit - und ich betone: ich tue das obwohl ich es für völlig überflüssig halte. Man braucht es nämlich nur dann wenn man die virtuellen Kanäle auf eine seltsame Art und Weise nutzt die nicht im Sinne des Erfinders liegt. Manuelle Bedienung kann (und sollte) einfach auf dem ersten der 3 virtuellen Kanäle stattfinden, dann bräuchte es diese Erweiterung nämlich gar nicht.
Eure Drängelei, Vorwurfs- und Anspruchshaltung ist auf jeden Fall ein spitzen Motivator weiter meine Sommerpause zu genießen und die Prioritäten bei der Open Source Arbeit wieder stärker auf Dinge zu richten die ich auch selbst haben möchte :-)

**Comment by spiu16** [comment]
Nicht ärgern, @hobbyquaker, es gibt glaube ich wirklich genügend Leute hier die deine Einstellung völlig nachvollziehen können und deine Arbeit entsprechend wertschätzen. Genieße deine Sommerpause, es gibt genügend andere Sachen die wichtiger sind (Familie,...).

**Comment by dehsgr** [comment]
Ich muss auch sagen, dass mich die eine oder andere Reaktion hier negativ überrascht. Da muss man sich doch glatt fremdschämen. @hobbyquaker, ich kann Dir nur beipflichten!

@CharlyFive, @Macem79 bitte überdenkt mal gehörig Eure Haltung! Hier wird ehrenamtlich für uns viel Zeit investiert und das mit einem hervorragenden Support. Ihr seid nicht alleine auf dieser Welt und solltet bedenken, dass Ihr für die Arbeit, die hier geleistet wird, nicht einen Cent zu bezahlen habt. Würdet Ihr eine kostenpflichtige Lizenz zur Nutzung zu erwerben haben, könnte ich Eure Haltung u.U. noch nachvollziehen, aber auch nur u.U. Also chilled mal ne Runde und überdenkt Euer Verhalten...

**Comment by vore** [comment]
@ hobbyquaker: genieß die Sommerpause und lass dich nicht ärgern! Vielen Dank für Deine Arbeit!

**Comment by CharlyFive** [comment]
Pass mal auf @hobbyquaker Ich habe dich ganz normal gefragt wann man mit der Erweiterung rechnen kann. Dazu habe ich noch betont das ich nicht drängeln will oder so. Ich wollte einfach nur wissen, wann ungefähr man damit rechnen kann. 

Aber du hast es ja für nötig gehalten, mir direkt sowas von ans Bein zu pinkeln statt einfach zu sagen "Hey, genieße gerade meine Sommerpause. Ich denke im Früh-Herbst ca. wird es dann soweit sein" oder so ähnlich. Dann hätte ich Dir einen schönen Sommer gewünscht und ich wäre schlauer gewesen. Aber wie gesagt, du musstest direkt deine Blase an meinem Bein entleeren.

So, und jetzt trotzdem einen schönen Urlaub.

**Comment by hobbyquaker** [comment]
ganz offensichtlich kannst und/oder willst Du es einfach nicht verstehen. Sei‘s drum, um jetzt zu versuchen es nochmal ausführlich für die etwas merkbefreiten Leute zu erklären ist mir meine Zeit zu schade.

**Comment by CharlyFive** [comment]
Oh, ich wusste nicht das man den König @hobbyquaker nichts fragen darf. Hätte ich deine Untertanen Fragen sollen? Oder ist Fragen komplett verboten?

Ich hoffe nicht, dass die anderen User die auch dieses feature haben wollen, durch meine absolut bodenlose und unverschämte Frage leiden müssen und das feature nicht bekommen.

**Comment by LevelOne2k** [comment]
@hobbyquaker Das wäre jetzt absolut übel wenn die Erweiterung wegen dieser Diskussion nicht mehr kommt. Denn auch ich möchte sie unbedingt haben und vermisse es sehr die anderen Kanäle auch wählen zu können. Ich hätte sie natürlich auch am liebsten gestern, aber ich habe Geduld und zudem in den Commits vom 15.07 gesehen das bereits dran gearbeitet wird.

**Comment by hobbyquaker** [comment]
@CharlyFive 

> 
nichts fragen darf.
welche Frage habe ich übersehen? In Deinem vorletzten Post gab es keine Frage, nur erneute Vorwürfe (und das auch in einem Tonfall den ich mir nicht gefallen lassen will: "Pass mal auf...").

> Dazu habe ich noch betont, dass ich nicht drängeln will 

Das hast Du - aber dennoch hast Du ein paar Zeilen weiter unten Formulierungen gewählt die in meinen Augen eben dann doch unverschämtes Gedrängel in einer unangebrachten Anspruchshaltung waren und damit die Aussage "ich will ja nicht drängeln" ad absurdum geführt haben:

> ... wann kann man denn nun mal...
> ... Zumindest wäre ein Kommentar deinerseits angebracht.

Merkst selber, ne? Mit Dir bin ich auf jeden Fall durch, kein Bock mich mit solchen Gestalten wie Dir auseinandersetzen zu müssen. Du verstehst vollkommen offensichtlich nicht wie freie open source Entwicklung funktioniert, Deine Kommunikationsfähigkeiten sind imho mangelhaft. Ich habe mich übrigens bereits an anderen Stellen an Dir gestoßen, aber mich bis zu diesem Ding hier immer bemüht geduldig zu sein. Jetzt reichts mir allerdings endgültig.

@LevelOne2k Überdenke bitte nochmal ob das wirklich nötig ist. Manuelle Bedienung ist eigentlich nur auf dem ersten der drei Virtuellen Kanäle vorgesehen. Interne Gerätetasten sind per Default auch nur mit diesem Kanal verknüpft. Das ganze ist doch recht viel Arbeit - und wie gesagt - ich brauch das für mich selbst nicht, daher hab ich da keine intrinsische Motivation. Wenn Du weiterhin absolut überzeugt bist dass dieses Feature für Dich unverzichtbar ist mach ichs fertig, aber mit der Bitte um Verständnis dass ich dem nicht die höchste Prio einräume und eben weiterhin gilt "it's done when it's done".

**Comment by LevelOne2k** [comment]
@hobbyquaker Ich habe den Präsenzmelder an den Dimmer an Kanal 5 mit Grund so verknüpft. Ich weiß allerdings nicht mehr warum ^^ es ist einfach zu lange her. Ich weiß aber, dass ich vor einiger Zeit den Präsenzmelder an den Dimmer an Kanal 4 verknüpft habe, im Alltag ist mir dann der Grund, warum er an Kanal 5 verknüpft wurde wieder aufgefallen.

Ich habe den Präsenzmelder jetzt nochmal an Kanal 4 von dem Dimmer direkt verknüpft. Ich werde jetzt wieder merken warum ich Kanal 5 gewählt habe und es Dir dann berichten. Danke schon mal.

**Comment by spiu16** [comment]
@CharlyFive wo hat hobbyquaker Dir denn ans Bein gepinkelt? Kann ich jedenfalls nicht erkennen. 
Such Dir doch eine andere Lösung für die HomeKit-Anbindung. Viel Erfolg dabei.

**Comment by LevelOne2k** [comment]
Hi @hobbyquaker Es wäre wirklich cool von dir, wenn Du das Feature implementieren würdest.

Vielen Dank Dir!

**Comment by hobbyquaker** [comment]
Für den HmIP-BDT steckt es in der aktuellen RedMatic Beta schon drin

**Comment by LevelOne2k** [comment]
Ah super. Vielen vielen Dank!

Kann ich die Beta evtl. installieren?

**Comment by hobbyquaker** [comment]
Wenn Du Dir bewusst bist dass das nicht ohne Grund als "Beta" bezeichnet wird, klar, warum nicht :-)
https://github.com/rdmtc/RedMatic/releases

**Comment by hobbyquaker** [comment]
=> #208
