### ISSUE TITLE
Pseudobutton mit KeyMatic -> Wie komplettes öffnen verhindern?

### ISSUE THREAD

**Issue by LevelOne2k** [rdmtc/RedMatic-HomeKit#160]
Hallo! Ich habe gerade einen Pseudobutton mit der KeyMatic verknüpft. Der Button soll die KeyMatic entriegeln, jedoch nicht komplett öffnen. Wie kann ich das in dieser Kombination realisieren?

Für die KeyMatic allgemein ist die Option "OpenOnUnlock" deaktiviert.
<img width="471" alt="Bildschirmfoto 2019-06-23 um 15 15 02" src="https://user-images.githubusercontent.com/25386824/59976811-bb9b6800-95c9-11e9-926a-9dcc48d6beb1.png">

<img width="454" alt="Bildschirmfoto 2019-06-23 um 15 13 07" src="https://user-images.githubusercontent.com/25386824/59976794-868f1580-95c9-11e9-8da6-33ced5e5dfbf.png">

<img width="500" alt="Bildschirmfoto 2019-06-23 um 15 12 46" src="https://user-images.githubusercontent.com/25386824/59976798-8c84f680-95c9-11e9-936c-da7a7a353308.png">

<img width="511" alt="Bildschirmfoto 2019-06-23 um 15 13 16" src="https://user-images.githubusercontent.com/25386824/59976801-927ad780-95c9-11e9-9969-64e48bacc6bc.png">

**Comment by hobbyquaker** [comment]
Dann musst Du den Datenpunkt `STATE` anstatt `OPEN` nutzen.

**Comment by LevelOne2k** [comment]
Der wird mir da nicht angeboten. Muss ich den dann manuell eintippen?

**Comment by hobbyquaker** [comment]
Hmm, das ist seltsam, der "sollte" erscheinen, bei mir funktioniert es zumindest:
<img width="572" alt="Bildschirmfoto 2019-07-02 um 00 39 34" src="https://user-images.githubusercontent.com/2503307/60470762-feaca980-9c61-11e9-8543-74513f623a61.png">

Möglicherweise ein Bug - muss ich Untersuchen. Manuell eintragen sollte aber auch funktionieren.

**Comment by LevelOne2k** [comment]
Ist kein Bug. Habe es angeboten bekommen. Alles gut danke.
