### ISSUE TITLE
implement HmIP-PSM-CH

### ISSUE THREAD

**Issue by VKTML** [rdmtc/RedMatic-HomeKit#161]
Das selbe Gerät wie HmIP-PSM, einfach Schweizer Stecker Version.
Währe super, wenn das aufgenommen werden könnte.
Cheers.

**Comment by hobbyquaker** [comment]
Wird im nächsten Release dabei sein, wenn Du nicht solange warten willst kannst Du schon vorab die Datei `/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/hmip-psm-ch.js` mit folgendem Inhalte anlegen:
```
module.exports = require('./hmip-psm');
```
Danach einmal Node-RED neustarten.

**Comment by VKTML** [comment]
Hammer, das nenn ich mal Service =D
Danke für die schnelle Antwort.

**Comment by dawiz77** [comment]
wow, vielen herzlichen Dank!
