### ISSUE TITLE
HMIP-BBL TiltAngle

### ISSUE THREAD

**Issue by 22kW** [rdmtc/RedMatic-HomeKit#168]
Hi, die Kippwinkel Einstellung meiner HMIP-BBL Raffstores (Aussenjalousien) funktioniert nicht über Homekit (direkt auf der Raspberrymatic GUI allerdings schon).
Nach Behanghöhenveränderung (über Homekit) wird immer der alte Winkel wieder hergestellt, aber nicht der, welchen ich über Homekit vorgebe. Eine reine Winkeländerung unter Homekit bewirkt überhaupt keine Aktion. Ideen ?

**Comment by hobbyquaker** [comment]
@22kW Hoffe das in RedMatic 5.0.0-beta.5 gefixt zu haben, kann es leider nicht selbst testen da ich das Gerät nicht habe... Bitte gib Bescheid ob es funktioniert.

**Comment by 22kW** [comment]
So, habe es heute mal kurz getestet, und es sieht schon mal sehr gut aus, vielen Dank !

**Comment by hobbyquaker** [comment]
@22kW Hast noch mehr Tests durchgeführt? Funktion ist einwandfrei gegeben? Können wir hier dann schließen?

**Comment by 22kW** [comment]
Funktioniert im Prinzip gut. Habe noch Probleme damit, dass der Kippwinkel bei einer Jalousie nicht reproduzierbar abweicht, aber da das auch über die Homematic WebUI auftritt liegt der Fehler wohl eher bei Homematic oder dem BBL Aktor selbst.
Zwei Anmerkungen noch:
1. Nach erreichen von 100% Höhe (also Jalousie ganz hoch) ist das Anfahren der Kippwinkelposition eigentlich überflüssig b.z.w sogar störend.Man kann da allerdings auch irgendwas im HMIP-BBL konfigurieren, hat aber bisher nicht geklappt.
2. Mir scheint, vor dem Start einer Fahrt zu einer neuen Behanghöhe wird erst noch der Kippwinkel verstellt. Da weiss ich nicht, ob das Redmatic oder Homematic macht, ist auf alle Fälle überflüssig.
