### ISSUE TITLE
Bridge wird mehrfach gepublished und crashed

### ISSUE THREAD

**Issue by kwithus** [rdmtc/RedMatic-HomeKit#169]
Ich habe heute red neu eingerichtet und anschließend redmatic-HomeKit installiert. Zunächst läuft alles relativ gut, abgesehen davon dass die ccu3 zu 26% und mehr ausgelastet ist und der Duty-Cycle hoch geht. Es dauert auch lange, bis der qr-Code in den Node-Einstellungen angezeigt wird. Die bridge wird dann in Home auch gefunden, aber dann stürzt red regelmäßig ab und entsprechend natürlich auch die Verbindung zur Bridge in Home. Wenn ich red neustarte, wird die Bridge trotzdem nicht mehr in Home gefunden (keine Verbindung).
Ich habe bereits die Bridge gelöscht und neu installiert und Redmatik-HomeKit de-installiert und neu installiert. Immer mit den gleichen Problemen.
Wo muss ich für den Fehler suchen?

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/RedMatic/wiki/Loglevel

**Comment by kwithus** [comment]
Danke, denke ich habe das Problem gefunden. Das iPad, das als Home-Zentrale definiert war, läuft mit der iOS 13 Beta (derzeit noch das 2. Build), das hatte ich vergessen. Ich habe dort Home-Zentrale de-aktiviert und mein „Haupt“iPad als Home-Zentrale definiert. Jetzt läuft es stabil. Ich werde jetzt einmal stückweise alle devices dazupacken.

**Comment by kwithus** [comment]
Da war ich wohl zu früh optimistisch.
Ich habe weiterhin Probleme die Bridge erfolgreich am Laufen zu halten. Sie schießt mir permanent red ab. Ich habe bereits alles komplett gelöscht, incl. dem Verzeichnis und alles neu installiert, neue Bridge angelegt. Es läuft alles, ich kann devices zufügen, taucht alles in Home auf und dann plötzlich ist die Verbindung weg und red gestoppt. 
[Safari - 06.08.2019, 14:26.pdf](https://github.com/rdmtc/RedMatic-HomeKit/files/3472218/Safari.-.06.08.2019.14.26.pdf)
Wenn ich red wieder starte, erscheint die Verbindung wieder in Home.
Aber stabil ist anders. Ich habe den Log-file angefügt.
Bin gespannt, wo der Fehler liegt

**Comment by hobbyquaker** [comment]
Das Log reicht nur von 14:11 bis 14:16 und beinhaltet leider nicht die Infos die ich bräuchte (es ist weder der Node-RED start, noch die HomeKit-Initialisierung und auch kein Absturz enthalten).
Starte mal bitte Node-RED noch mal neu, warte bis es wieder crasht und mach dann nochmal ein Log Download. (Musst es übrigens auch nicht in einem pdf verpacken, Du kannst es hier einfach pasten, vor die erste und hinter die letzte Zeile bitte ``` setzen)

**Comment by kwithus** [comment]
Ok, hier ein neues log, wieder als pdf, da ich es sonst nicht posten kann/darf (zu viele Zeichen)
Müsste erst die Bridge löschen und neun legen, da die Verbindung weg war und auch Neustart von Node-red nichts brachte- neu angelegt, mit einem Device, alles ok, zweites Device zugefügt, Absturz. Bin ziemlich gefrustet, versuche den ganzen Tag es zum Laufen zu bringen, es geht immer eine Weile, dann Verbindungsabbruch und das völlig unsystematisch. Ich kann z.B. Nicht bestätigen, dass es an bestimmten devices liegt.
[Safari - 06.08.2019, 18:10.pdf](https://github.com/rdmtc/RedMatic-HomeKit/files/3473178/Safari.-.06.08.2019.18.10.pdf)

**Comment by kwithus** [comment]
Kurze Ergänzung: das Verhalten nach Absturz ist auch völlig unsystematisch. Manchmal reicht Neustart um die Verbindung wieder zu haben, manchmal muss ich zusätzlich Device dazugäben oder löschen, und manchmal hilft gar nichts, außer löschen und neu anlegen

**Comment by hobbyquaker** [comment]
Das Log hilft mir leider wieder nicht, umfasst nur den Zeitraum von einer Minute (während Node-RED gerade beendet wird). Bist Du Dir sicher dass da alles im pdf gelandet ist?

**Comment by hobbyquaker** [comment]
Wenn das hier nicht klappt schick mir einfach die runtergeladene .log Datei an hobbyquaker@gmail.com

**Comment by kwithus** [comment]
Anbei eine neue log-Datei, habe sie auch per Mail geschickt. Sorry, dass ich nicht vorher kontrolliert hatte, ob alles im pdf gelandet ist.
[log.txt](https://github.com/rdmtc/RedMatic-HomeKit/files/3473801/log.txt)

**Comment by hobbyquaker** [comment]
Ok, ich seh da zwei Probleme. Einmal (aber das hat erstmal nix mit dem HomeKit Problem zu tun) schlägt dass Parsen fehl beim Abfragen der Systemvariablen:
`getRegaVariables Error: JSON.parse failed. Saved debug data to /tmp/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/scripts/variables.rega.failed.json`
Um diesen Fehler zu analysieren bräuchte ich mal den Inhalt der Datei `/tmp/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/scripts/variables.rega.failed.json`.

Und dann gibt es noch ein weiteren Bug bzw. eine nicht abgefangene Situation die dann zum Crash führt:
```
Error: This callback function has already been called by someone else; it can only be called one time.
Aug  6 21:06:40 ccu3-webui daemon.err node-red:     at /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/node_modules/hap-nodejs/lib/util/once.js:12:13
Aug  6 21:06:40 ccu3-webui daemon.err node-red:     at Characteristic.ContactSensorState.addListener.callback
```

Hier wird versucht den geänderten Status eines Kontaktsensors an die Bridge zu übermitteln, das darf nur einmal passieren, wird hier aber doppelt gemacht. Verursacht wird das indirekt vom ersten Problem. Was da abläuft ist dass die Bridge nach jedem Auftreten des ersten Fehlers dazu veranlasst wird die Geräte erneut zu publishen, das darf aber nur einmal passieren sonst führt es eben zum zweiten Fehler, ich werde das in Zukunft verhindern, dennoch sollten wir auch den ersten Fehler beheben.

Als schnellen Workaround könntest Du erstmal das Interface ReGaHSS im ccu-connection Node deaktivieren (https://github.com/rdmtc/RedMatic/wiki/CCU-Nodes#ccu-connection-node), dann sollte es laufen.

**Comment by kwithus** [comment]
Ok, ReGaHSS habe ich deaktiviert und prompt wieder Verbindung gehabt.
Den Hinweis auf die fragliche json hatte ich auch schon gesehen, allerdings Problem: in Verzeichnis tmp sehe ich kein Vereichnis usr!?
Ich nutze Code Editor am iPad und habe hidden files auf sichtbar gestellt.




Suche ich an der falschen Stelle?
Gruß
K-H
Von meinem iPad gesendet

**Comment by hobbyquaker** [comment]
ah verdammt, ne, Du suchst an der richtigen Stelle, aber die Datei existiert gar nicht. Auch ein Fehler den ich noch beheben muss. Ich meld mich wenn das erledigt ist, dann würd ich Dich bitten ReGaHSS nochmal zu aktivieren und dann nochmal zu schauen. Kann aber noch dauern.

**Comment by kwithus** [comment]
Kein Thema, jedenfalls kann ich das Projekt HomeKit jetzt erstmal guten Gewissens zur Seite legen. Dachte ja die ganze Zeit, ich bin zu blöd es zum Laufen zu bringen ;-)
Ist nicht schlimm, wenn das est später läuft. Gibt ja bei smarthome immer genügen andere Baustellen zum Basteln 😂
Sag Bescheid, wenn das Update fertig ist.
Gruß
K-H


Von meinem iPad gesendet

**Comment by kwithus** [comment]
Nur noch als Ergänzung, nach Deaktivierung der ReGaHSS haben die devices keine Namen mehr, sondern werden nur noch unter ihren ID angezeigt. Dies aber auch nur in Node red HomeKit, nach HomeKit wird nichts importiert, nur die Bridge selbst ist zu sehen.
Könnte ich erst nicht sehen, da alle Device in HomeKit angezeigt wurden, erst beim nächsten Hinzufügen von devices (enable all), verschwanden dann alle devices in HomeKit.
Scheint, dass dear workaround so nicht funzt. Ist aber wie gesagt nicht dramatisch. Ich warte einfach ab.
K-H


Von meinem iPad gesendet

**Comment by hobbyquaker** [comment]
Oh, klar, da hab ich nicht weit genug gedacht. Versuchs mal so: ReGaHSS aktiviert lassen aber ReGa Polling deaktivieren.

**Comment by kwithus** [comment]
Klappt

Von meinem iPhone gesendet
