### ISSUE TITLE
Homebridge Plugins benutzbar?

### ISSUE THREAD

**Issue by hdiessner** [rdmtc/RedMatic-HomeKit#174]
Hallo und danke für das tolle Projekt.
Meine Frage ist: Kann ich für homebridge verfügbare Plugins irgendwie in Redmatic-Homekit einbinden und verwenden?
Konkret möchte ich aktuell einen Xiaomi Mi Fan2 einbinden, am liebsten wäre mir direkt in Redmatic. Aber dafür gibt es wohl noch keine funktionierende Lösung. Aber für homebridge gibt es ein funktionierendes Plugin. Wie kann ich dieses unter Redmatic-Homekit einbinden? Das dürfte evtl. grundsätzlich auch für andere derartige Plugins interessant sein.
Im Wiki und bei den bisherigen Issues habe ich dazu leider nichts gefunden.

**Comment by hobbyquaker** [comment]
Nein, das ist nicht vorgesehen. Der Weg den ich vorschlagen würde ist: Binde den Fan in Node-RED ein (insofern es da Nodes gibt die das ermöglichen, aber ich denke mit den miio-basierten Nodes "sollte" das gehen) und verbinde diese dann mit dem RedMatic-HomeKit "Universal Accessory".
