### ISSUE TITLE
Wie redmatic-homekit Paket updaten?

### ISSUE THREAD

**Issue by LevelOne2k** [rdmtc/RedMatic-HomeKit#175]
Hallo! Ich sehe hier das die Version 2.4.1 aktuell ist. Ich habe Version 2.3.3 installiert. Wie kann ich auf die 2.4.1 updaten? THX

**Comment by hobbyquaker** [comment]
An eine bestimmte RedMatic Version ist immer eine bestimmte Version von RedMatic-HomeKit gebunden. Du kannst also nur RedMatic upgraden und das bringt dann eine neue RedMatic-HomeKit Version mit, RedMatic-HomeKit einzeln aktualisieren geht nicht.
