### ISSUE TITLE
Bitte "ZEL STG RM FEP 230V" integrieren

### ISSUE THREAD

**Issue by HJS72** [rdmtc/RedMatic-HomeKit#177]
Gerät entspricht 1:1 dem Rolladenaktor HM-LC-Bl1-FM. Wurde unter der oben genannten Bezeichnung von Roto vertrieben und kann in der ccu vollwertig als Rolladenaktor betrieben werden.
<img width="800" alt="Screenshot 2019-09-11 17 54 54" src="https://user-images.githubusercontent.com/41542201/64713622-7e09f500-d4bd-11e9-8b45-6f8b2bbbc51d.png">

**Comment by hobbyquaker** [comment]
@HJS72 bitte versuch mal folgendes:
Die Datei `/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/zel stg rm fep 230v.js` anlegen (mit Leerzeichen im Dateinamen!) mit folgendem Inhalt:
```
module.exports = require('./hm-lc-bl1-fm');
```

Danach einmal Node-RED Neustart und schauen ob das Gerät in HomeKit verfügbar ist.

**Comment by HJS72** [comment]
<img width="615" alt="Screenshot 2019-10-01 19 26 52" src="https://user-images.githubusercontent.com/41542201/65985107-75d02480-e481-11e9-8bb8-46f9ac449670.png">

Datei mit entsprechendem Inhalt angelegt, Node-RED neu gestartet. Leider keine neuen Geräte im HomeKit verfügbar

**Comment by hobbyquaker** [comment]
@HJS72 kannst Du mir mal bitte ein Log auf Debug Level zeigen beim Start von Node-RED.

**Comment by hobbyquaker** [comment]
Hab Dein Log eben angeschaut, leider geb ich die notwendige Info da gar nicht aus :-(
Bitte mach mal folgendes: nimm ein "RPC Event" Node, konfigurier den so dass er Events von dem Rollladenaktor ausgibt, schließ ein "Debug" Node an und konfigurier den auf "complete msg object". Dann fahr mal den Rollladen und zeig die Ausgabe im Debug Tab, in der Nachricht die da dann erscheinen müsste stehen die nötigen Infos drin.

**Comment by hobbyquaker** [comment]
@HJS72 kannst mir mal noch bitte die Dateien `/usr/local/addons/redmatic/var/ccu_paramsets_v2.json` und `/usr/local/addons/redmatic/var/ccu_localhost.json` mailen?

**Comment by Lasso77** [comment]
Ich hänge mich hier mal mit rein, da ich dasselbe Problem habe. Bin vor kurzem von der CCU2 auf einen Raspi 3b mit Raspberrymatic in Verbindung mit deinem wirklich grandiosen Node Red Addon für Homekit umgestiegen. Wirklich tolle Arbeit, ganz herzlichen Dank dafür!
Habe einen HM-LC-Bl1-FM für die Steuerung unserer Markise im Einsatz, der zuvor von der originalen CCU auch als solcher ausgewiesen wurde. Nach Einspielen meines CCU Backups wird dieser in Raspimatic nun mysteriöserweise als ein ZEL STG RM FEP 230V angezeigt, der zwar genauso bedienbar bleibt wie zuvor, jedoch in Redmatic nicht als Device auftaucht. Wäre für eine Hilfestellung sehr dankbar!

**Comment by hobbyquaker** [comment]
@Lasso77 @HJS72  Ich bräuchte noch diese Dateien
`/usr/local/addons/redmatic/var/ccu_paramsets_v2.json`
`/usr/local/addons/redmatic/var/ccu_localhost.json`
(hobbyquaker@gmail.com)

Mit den Infos da drin kann ich denke ich schnell den ZEL STG... integrieren.

**Comment by hobbyquaker** [comment]
@Lasso77 @HJS72 Versucht mal bitte ob es mit RedMatic 5.0.3 funktioniert.

**Comment by HJS72** [comment]
@hobbyquaker 5.0.3 installiert. Leider sind die Geräte im Homematic Node nicht verfügbar.

**Comment by hobbyquaker** [comment]
schickst mir bitte nochmal ein debug log?

**Comment by HJS72** [comment]
@hobbyquaker Mail ist raus

**Comment by HJS72** [comment]
Hab gerade festgestellt, dass ich auf dem Handy in der Home App die Rollladen sehe.
Kann sie nur in RedMatic nicht selektieren zur An-/Abwahl.

**Comment by Lasso77** [comment]
Ich kann vermelden, dass der Aktor mit dem Update auf RedMatic 5.0.3  jetzt bei mir wie von Geisterhand als funktionierendes Accessory in Homekit auftaucht.
Von Geisterhand deswegen, weil der Aktor im Homematic Node wie bei @HJS72 auch nach dem Update nirgends in der Geräteliste zu sehen ist, so als würde er in der Konfiguration nicht existieren. Aber es funktioniert. Vielen Dank!

**Comment by jpawlowski** [comment]
Ich habe noch ein weiteres ZEL Gerät und habe dafür PR #212 erstellt.

**Comment by jpawlowski** [comment]
In PR #213 habe ich außerdem einen Eintrag für ZEL STG RM FEP 230V hinzugefügt (wahrscheinlich nur der Vollständigkeit halber, aber trotzdem :-))
