### ISSUE TITLE
HMIP-FBL

### ISSUE THREAD

**Issue by github6043** [rdmtc/RedMatic-HomeKit#180]
Hi all
Habe Debmatic in der aktuellen Version und Node Red als je eine VM am drehen. Klappt soweit alles. Habe zur Jalousiesteuerung den Bericht gesehen. Kann diese Lösung auch in Debmatic integriert werden ?

**Comment by hobbyquaker** [comment]
Ich verstehe leider nicht ganz worauf Du rauswillst. Ist die Frage ob man RedMatic-HomeKit auch abseits von RedMatic nutzen kann? Falls ja: das sollte gehen, einfach Node-RED, node-red-contrib-ccu sowie RedMatic-HomeKit installieren.
