### ISSUE TITLE
HM-Sen-DB-PCB "Nicht unterstützt"

### ISSUE THREAD

**Issue by LevelOne2k** [rdmtc/RedMatic-HomeKit#181]
Hallo, das Gerät HM-Sen-DB-PCB (Klingelsensor) wird laut Home App nicht unterstützt.

![A7962480-C708-46C8-9B39-71EB824651CF_1_201_a](https://user-images.githubusercontent.com/25386824/66075107-2827ea80-e55b-11e9-8d69-c8cfc1fa07a7.jpeg)

![936F8EE1-7557-4F05-B04F-124C09564417_1_201_a](https://user-images.githubusercontent.com/25386824/66075108-2827ea80-e55b-11e9-8a82-7dcda390564c.jpeg)

**Comment by hobbyquaker** [comment]
Das ist so, ist eine Eigenheit von HomeKit, kein Bug. Die Home.app kann damit erstmal nichts anfangen, aber Du solltest dennoch eine Benachrichtigung über das Message Center erhalten wenn es klingelt.

Der Doorbell Service ist insbesondere in Kombination mit einer Kamera sinnvoll, dann bekommst Du eine Nachricht in der direkt ein Snapshot des Kamerabildes steckt und die beim Öffnen direkt zur Kameraansicht in der Home.app führt. Damit das funktioniert muss die Klingel dem gleichen Raum wie die Kamera zugeordnet sein.

**Comment by LevelOne2k** [comment]
Eine Push Nachricht bekomme ich wenn es Klingelt. Das Kamerabild wird jedoch nicht angezeigt. Beide Geräte befinden sich im Raum "Flur".

**Comment by hobbyquaker** [comment]
Für den Snapshot des Kamerabildes muss ich noch Anpassung an iOS 13 vornehmen. Ich schließe hier, wird in #198 getracked.
