### ISSUE TITLE
Heizthermostat bzw. Heizkörperthermostat wird immer auf Modus "Auto" gestellt

### ISSUE THREAD

**Issue by LevelOne2k** [rdmtc/RedMatic-HomeKit#182]
Hallo, immer wenn ich die Temperatur über Siri ändere z.B. von 16° auf 20° und der Modus auf Manuell steht, ist alles in Ordnung. Wenn ich die Temperatur bzw. die Heizung über Siri ausschalte, funktioniert das auch, jedoch wenn ich sie dann wieder einschalte z.B. per "Hey Siri stelle die Temperatur im Raum XY auf 20°" dann funktioniert das auch, jedoch wird dann der Modus "Auto" eingeschaltet statt "Manu". 

@hobbyquaker Hast Du da Einfluss drauf, dass der Modus nicht geändert wird, wenn die Heizung auf "Aus" steht und man sie dann über einen Temperatur Befehl einschaltet?

Z.B. Das man hier noch die Option hat in welchen Modus von Staus "Aus" gewechselt werden soll, ob in "Auto" oder "Manu".
<img width="484" alt="Bildschirmfoto 2019-10-02 um 21 42 16" src="https://user-images.githubusercontent.com/25386824/66076212-98377000-e55d-11e9-8a68-e94112c967fd.png">

**Comment by LevelOne2k** [comment]
@hobbyquaker Ist es ein Bug?

**Comment by hobbyquaker** [comment]
Ist ein Bug, ich konnte es ein paar mal reproduzieren, aber nicht zuverlässig, meistens trat es nicht auf. Noch keine Ahnung wie das Zustande kommt... Muss noch um Geduld bitten.

**Comment by AdlerCentauri** [comment]
Hallo zusammen. Gibt es diesbezüglich schon etwas neues? Ich habe das Problem leider auch. Danke schon mal

**Comment by TheRealTremes** [comment]
@hobbyquaker bei mir verhält es sich genauso wie bei @LevelOne2k. 

Wenn die Heizung auf Manu steht und ich sie mit Siri ausschalte, dann wieder einschalte, steht der Modus auf Auto statt auf Manu wie es vorher war.

**Comment by hobbyquaker** [comment]
Habe grade noch ein bisschen geforscht - und ich befürchte ich kann daran nichts ändern. Insofern in der Home.app alles richtig funktioniert (was es in meinen Tests eben tat) gibt es keinen Bug in RedMatic-HomeKit. Einfluß darauf nehmen bei welcher Wortwahl Siri welche Aktion ausführt ist nicht möglich. Es ist jedoch durchaus möglich auch mit Siri gezielt in den manuellen Modus zu wechseln, z.B. mit dem Satz`Stelle Heizung <Name> auf heizen`. Ebenso kann man Siri auch gezielt auffordern auf automatik umzustellen, z.B. mit dem Satz `Stelle Heizung <Name> auf Automatik`.
