### ISSUE TITLE
HmIP-STHD & HmIP-FAL Zieltemperatur mit Homekit steuern

### ISSUE THREAD

**Issue by decodrr** [rdmtc/RedMatic-HomeKit#186]
Hallo @hobbyquaker,

ich betreibe in meinem Haus vier HmIP-FAL Steuereinheiten für die Fußbodenheizung auf vier Etagen. Alle Räume sind mit HmIP-STHD zur Messung der Ist-Temp ausgestattet.

Im HmIP-AP konnte ich die Zieltemperatur über die App steuern, siehe Screenshot.

In Homekit wird mir jedoch nur die Ist-Temp angezeigt und ich kann nicht die Ziel-Temp steuern (Screenshot 2), obwohl das im CCU3-Web so eingerichtet ist und dort auch funktioniert.

Besteht für Dich die Möglichkeit die Funktion in RedMatic-Homekit nachzurüsten?

Besten Dank! 

![IMG_6372](https://user-images.githubusercontent.com/56485728/66705598-26afac80-ed29-11e9-9d16-03d60077eefb.jpg)

![IMG_DB32087C0C07-1](https://user-images.githubusercontent.com/56485728/66705611-5494f100-ed29-11e9-9910-5654ff9d2d56.jpeg)

**Comment by Mrgrafcox** [comment]
Würde mich ebenfalls interessieren.
Gruss

**Comment by hobbyquaker** [comment]
Ist auf der Todo. Ich schließe hier, wird in #190 behandelt.
