### ISSUE TITLE
HMW-IO-12-Sw7-DR wird in Node Red nicht angezeigt

### ISSUE THREAD

**Issue by Hoefti1980** [rdmtc/RedMatic-HomeKit#187]
Hallo,

bei mir wird leider der HMW-IO-12-Sw7-DR nicht in Node-RED angezeigt obwohl er ja zu den unterstützten Geräten gehört.
Muss ich den noch anders aktivieren?
Ist meine erste wired Komponente.

Habe schon über ssh folgendes probiert, leider ohne Erfolg:
module.exports = require('./lib/generic-switch');

Gruß und vielen Dank 
Hoefti

**Comment by hobbyquaker** [comment]
Hast Du Bidcos-Wired im ccu-connection Node aktiviert? https://github.com/rdmtc/RedMatic/wiki/CCU-Nodes#ccu-connection-node

**Comment by Hoefti1980** [comment]
Jetzt ja, funktioniert :-).
Dankeschön!
