### ISSUE TITLE
Config-Möglichkeit für HmIP-STHD/O als Thermostat oder nur als Sensor

### ISSUE THREAD

**Issue by klingbing** [rdmtc/RedMatic-HomeKit#190]
Mir fiel auf, dass Ist-/Solltemperatur und Luftfeuchtigkeit eines HmIP-STHD (an Falmot-C12) in Homekit zwar angezeigt werden, eine Steuerung der FBH (Aus/Heizung/Automatisch und Temperatur), in Homekit jedoch nicht möglich ist. Ist dies vielleicht eine Einschränkung der Hardware (HmIP-STHD im Gegensatz zum HmIP-WTH2)?  
In der @Home 2.0 App wird zwischen diesen beiden Geräten nicht unterschieden, über diese App kann ich sowohl HmIP-STHD als auch HmIP-WTH2 vollständig steuern.

**Comment by hobbyquaker** [comment]
Du kannst als schnellen Workaround die Datei `/usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/homematic-devices/hmip-sthd.js` ändern in:
```
module.exports = require('./hmip-wth');
```
Für eine Dauerhafte Lösung muss ich für den HmIP-STHD/O noch eine Configmöglichkeit anbieten da er ja auch rein als Sensor und nicht als Thermostat betrieben werden kann.

**Comment by klingbing** [comment]
@hobbyquaker Danke für die schnelle Reaktion und den Workaround, das hat gut funktioniert, das STHD kann ich nun steuern. Ich würde jetzt gern noch den BoostSwitch für die STHD deaktivieren, habe jedoch im Homematic Node keine Einstellungsmöglichkeit. Gibt es dafür auch einen Workaround?

**Comment by hobbyquaker** [comment]
Da muss ich noch im Geduld bitten, ließe sich nur durch manuelles editieren der homekit-homematic config abstellen, aber davon würde ich abraten.

**Comment by Mrgrafcox** [comment]
@klingbing könntest du einem Anfänger wie ich erklären wo ich diese Datei finde bzw wie ich den workaround ausführen kann ;-)
Viele Grüsse
