### ISSUE TITLE
HMIP-MOD-OC8: "SingleAccessory" Checkbox ohne Effekt

### ISSUE THREAD

**Issue by klingbing** [rdmtc/RedMatic-HomeKit#192]
Die 8 Kanäle des HMIP-MOD-OC8 erscheinen in Homekit immer als ein Gerät/gebündelt, das Deaktivieren der "SingleAccessory" Checkbox hatte dabei kein Effekt. 

Zuletzt getestet unter v5.0.5, Restart und Reboot erfolglos.

**Comment by hobbyquaker** [comment]
Hast Du nach der Konfigurationsänderung und dem Deploy auch Node-RED neugestartet (siehe https://github.com/rdmtc/RedMatic/wiki/Homekit#nutzungshinweise) und iOS etwas Zeit gelassen?

**Comment by klingbing** [comment]
Ja, ich habe in der Zwischenzeit mehrfach deployed und Node-RED neugestartet, auch die Redmatic Releases wurden immer fleißig aktualisiert - nur 5.2.2 habe ich noch nicht installiert, mache ich heute abend.

**Comment by klingbing** [comment]
Auch unter 5.2.2 keine Veränderung. Ich habe auch versucht, die SingleAccessory Checkbox zu aktivieren, deploy und restart und anschließend die Checkbox wieder deaktiviert (und auch wieder deploy und restart durchgeführt), ohne Erfolg. 

Nach einem Update auf iOS 13.2.3 habe ich jetzt zwar die Möglichkeit "Als separate Felder anzeigen" auszuwählen, ich kann dann jedoch nicht für die einzelnen HMIP-MOD-OC8 Geräte unterschiedliche Räume auswählen...

**Comment by hobbyquaker** [comment]
@klingbing Sollte mit RedMatic 5.3.1 gefixt sein. Bitte gib Bescheid ob es funktioniert.

**Comment by klingbing** [comment]
Jetzt funktioniert es, vielen Dank - und guten Rutsch!

**Comment by stefanfejfar** [comment]
> Nach einem Update auf iOS 13.2.3 habe ich jetzt zwar die Möglichkeit "Als separate Felder anzeigen" auszuwählen, ich kann dann jedoch nicht für die einzelnen HMIP-MOD-OC8 Geräte unterschiedliche Räume auswählen...

Das gleiche Phänomen habe ich bei meinen HmIPW-DRS4 / DRS8 Aktoren.
Auch mit dem neuesten Release 5.3.1 sowie neu deployen und Restart lassen sich die Kanäle nicht einzelnen Räumen zuordnen, sondern die Raumänderung eines Kanals ändert auch alle Räume der anderen Kanäle des Aktors.

**Comment by hobbyquaker** [comment]
#240
