### ISSUE TITLE
HmIP-FDT Schaltstatus synchronisiert nicht zwischen HomeMatic und HomeKit

### ISSUE THREAD

**Issue by lacalamine64** [rdmtc/RedMatic-HomeKit#193]
Hallo,

ich habe bereits HmIP-PDT in Gebrauch und die funktionieren wunderbar. Heute habe ich eine Lampe mit einem HmIP-FDT ausgestattet und habe damit Probleme.

Konkret wird der Schaltstatus nicht zwischen HomeMatic und HomeKit synchronisiert. Wenn ich den Aktor über das Web-Interface schalte, wird der Zustand in der Home App nicht geändert und vice versa.
Beispiel:
- Einschalten über Home App > Lampe leuchtet
- Web-Interface zeigt sie ausgeschaltet, hier einschalten > Lampe leuchtet weiterhin
- Ausschalten über Home App > Lampe leuchtet weiterhin
- Web-Interface zeigt sie eingeschaltet, hier ausschalten > Lampe leuchtet nicht

Mein Vermutung wäre die hmip-fdt.js. Wie ich das sehe, verweist diese lediglich auf die hmip-pdt.js und das funktioniert so vielleicht nicht?

Vielen Dank schon mal für die Hilfe und ein riesiges Dankeschön für dieses klasse Projekt!

**Comment by lacalamine64** [comment]
Kurze Ergänzung: mein HmIP-BDT funktioniert auch einwandfrei. Dessen hmip-bdt.js ist ja ebenfalls ausführlich, wie des HmIP-PDT

**Comment by hobbyquaker** [comment]
Sollte mit RedMatic 5.2.1 gefixt sein. @lacalamine64 bitte Bescheid geben ob es wie erwartet funktioniert.

**Comment by lacalamine64** [comment]
@hobbyquaker: funktioniert soweit einwandfrei. Vielen dank für die schnelle Behebung!
