### ISSUE TITLE
TRADFRI bulb E14 WS opal 600lm wird nicht an HomeKit übertragen

### ISSUE THREAD

**Issue by sandrazip** [rdmtc/RedMatic-HomeKit#197]
Hallo, ich verzweifle an der HomeKit-Einbindung einer Ikea Tradfri-Birne. 

Mein Setup:

- CCU3 mit CC2531 Zigbee-Stick
- RedMatic 5.2.0
- node-red-contrib-zigbee 0.15.0
- redmatic-homekit 2.6.0
- Tradfri LED E14 LED1733G7 (TRADFRI bulb E14 WS opal 600lm)

Die Birne lässt sich am CC2531 anlernen und wird an der zigbee-controller-node angezeigt, ebenso in der Network Map.

![image](https://user-images.githubusercontent.com/57100126/67687211-45a07680-f998-11e9-875a-158dacd6a312.png)

An der HomeKit-Zigbee-node taucht die Birne jedoch nicht auf und wird somit auch nicht an HomeKit übertragen.

Ein ebenso am CC2531 angelernter Osram Smart+ Plug wird an der HomeKit-Zigbee-node angezeigt und korrekt an Homekit übertragen.

![image](https://user-images.githubusercontent.com/57100126/67687363-7d0f2300-f998-11e9-9b30-fb2e45fa4fc2.png)

Wird die Tradfri-Birne ggf. noch nicht unterstützt?

Grüße, Sandra

device info zigbee-controller-node
```
{
    "ieeeAddr": "0x14b457fffe3e4252",
    "applicationVersion": 32,
    "dateCode": "20190308",
    "endpoints": [
        {
            "ID": 1,
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "modelId": "TRADFRI bulb E14 WS opal 600lm",
                        "manufacturerName": "IKEA of Sweden",
                        "powerSource": 1,
                        "zclVersion": 2,
                        "appVersion": 32,
                        "stackVersion": 98,
                        "hwVersion": 1,
                        "dateCode": "20190308",
                        "swBuildId": "2.0.022"
                    }
                }
            },
            "deviceNetworkAddress": 36346,
            "deviceIeeeAddr": "0x14b457fffe3e4252",
            "inputClusters": [
                0,
                3,
                4,
                5,
                6,
                8,
                768,
                4096,
                64636
            ],
            "outputClusters": [
                5,
                25,
                32,
                4096
            ],
            "profileID": 260,
            "binds": []
        },
        {
            "ID": 242,
            "clusters": {},
            "deviceNetworkAddress": 36346,
            "deviceIeeeAddr": "0x14b457fffe3e4252",
            "inputClusters": [
                33
            ],
            "outputClusters": [
                33
            ],
            "profileID": 41440,
            "binds": []
        }
    ],
    "hardwareVersion": 1,
    "interviewCompleted": true,
    "interviewing": false,
    "lastSeen": 1572271567164,
    "manufacturerID": 4476,
    "manufacturerName": "IKEA of Sweden",
    "modelID": "TRADFRI bulb E14 WS opal 600lm",
    "networkAddress": 36346,
    "powerSource": "Mains (single phase)",
    "softwareBuildID": "2.0.022",
    "stackVersion": 98,
    "type": "Router",
    "zclVersion": 2,
    "meta": {
        "offline": false
    }
}
```

**Comment by hobbyquaker** [comment]
Ich nehms auf die Todo, muss aber um etwas Geduld bitten.

**Comment by hobbyquaker** [comment]
@sandrazip Du könntest aber schon vorab versuchen die Schritte die ich in #189 beschrieben hab durchzuführen (modelID entsprechend anpassen)

**Comment by sandrazip** [comment]
@hobbyquaker Ja das hat geklappt, vielen Dank!

**Comment by kneip68** [comment]
Beispielflow für den Bewegungsmelder mit angeschlossenem Homematik Schalter:
`[{"id":"aaf601a0.28b51","type":"zigbee-event","z":"3622156e.ab937a","shepherd":"","name":"Bewegungsmelder","device":"0x14b457fffe694633","events":["attributeReport","command"],"topic":"zigbee/${ieeeAddr}/${type}/${endpoint}/${cluster}/${attribute}","payload":"json","x":290,"y":220,"wires":[["e0a5d0e4.2c39"]]},{"id":"3855f74d.80f848","type":"ccu-value","z":"3622156e.ab937a","name":"Eingangslicht","iface":"BidCos-RF","channel":"OEQ1012250:1 Licht Eingang","datapoint":"STATE","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":"ontime","onType":"msg","ramp":0,"rampType":"undefined","working":true,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":1080,"y":280,"wires":[[]]},{"id":"e0a5d0e4.2c39","type":"sun-position","z":"3622156e.ab937a","name":"SunInSky","positionConfig":"","rules":[],"onlyOnChange":"true","topic":"","outputs":1,"start":"blueHourDawnStart","startType":"pdsTime","startOffset":0,"startOffsetType":"none","startOffsetMultiplier":60000,"end":"goldenHourDuskStart","endType":"pdsTime","endOffset":0,"endOffsetType":"none","endOffsetMultiplier":60000,"x":480,"y":280,"wires":[["131fc398.cbf12c"]]},{"id":"131fc398.cbf12c","type":"switch","z":"3622156e.ab937a","name":"Nur Nachts","property":"payload.sunInSky","propertyType":"msg","rules":[{"t":"false"}],"checkall":"false","repair":false,"outputs":1,"x":650,"y":280,"wires":[["501f1f47.faccb"]]},{"id":"501f1f47.faccb","type":"change","z":"3622156e.ab937a","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"true","tot":"bool"},{"t":"set","p":"ontime","pt":"msg","to":"300","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":860,"y":280,"wires":[["3855f74d.80f848"]]},{"id":"6ec9dcff.1528f4","type":"comment","z":"3622156e.ab937a","name":"Lichtschaltung","info":"","x":230,"y":180,"wires":[]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048"}]`
