### ISSUE TITLE
Neues Homematic Gerät HmIP-MOD-HO 

### ISSUE THREAD

**Issue by kwithus** [rdmtc/RedMatic-HomeKit#201]
Bitte in HomeKit einbinden, danke!

**Comment by hobbyquaker** [comment]
Ist in RedMatic 5.2.1 hinzugefügt - allerdings im Blindflug entwickelt und ungetestet. @kwithus bitte Bescheid geben ob es wie erwartet funktioniert.

**Comment by kwithus** [comment]
Funktioniert teilweise, Gerät wird erkannt, Status offen/geschlossen wird angezeigt.
Das Gerät hat noch einen dritten Status (Lüftungsposition), dieser wird nicht erkannt / angezeigt.
Befehle aus HomeKit heraus (derzeit nur öffnen/schließen, es fehlt logischerweise auch hier Lüftungsposition) wird nicht nach Homematic übertragen, dh. In Home wird „wird geöffnet“ angezeigt, es tut sich aber nichts.
Das Gerät hat außerdem noch 2. Kanal für Licht an/aus, der fehlt noch.
Anbei einmal alle von mir ausgelesenen Datenpunkte


HmIP-RF.00241A499DE23C:0.CONFIG_PENDING
HmIP-RF.00241A499DE23C:0.DUTY_CYCLE
HmIP-RF.00241A499DE23C:0.OPERATING_VOLTAGE
HmIP-RF.00241A499DE23C:0.OPERATING_VOLTAGE_STATUS
HmIP-RF.00241A499DE23C:0.RSSI_DEVICE
HmIP-RF.00241A499DE23C:0.RSSI_PEER
HmIP-RF.00241A499DE23C:0.UNREACH
HmIP-RF.00241A499DE23C:0.UPDATE_PENDING
HmIP-RF.00241A499DE23C:1.DOOR_COMMAND
HmIP-RF.00241A499DE23C:1.DOOR_STATE
HmIP-RF.00241A499DE23C:1.ERROR_CODE
HmIP-RF.00241A499DE23C:1.PROCESS
HmIP-RF.00241A499DE23C:1.SECTION
HmIP-RF.00241A499DE23C:1.SECTION_STATUS
HmIP-RF.00241A499DE23C:2.PROCESS
HmIP-RF.00241A499DE23C:2.SECTION
HmIP-RF.00241A499DE23C:2.SECTION_STATUS
HmIP-RF.00241A499DE23C:2.STATE

Mögliche Aktionen für 1 sind : Tor öffnen / Fahrt stoppen / Tor schließen / Stellung Lüftungsposition 
Mögliche Zustände für 1 sind: Stellung geöffnet / Stellung geschlossen /Lüftungsposition / Stellung unbekannt (Letztere liegt an, wenn das Tor in Bewegung ist
Mögliche Aktionen für 2:Schaltzustand:Ein / Schaltzustand: Aus
Mögliche Zustände für 2 Schaltzustand: Ein / Schaltzustand: Aus

Hoffe, das hilft weiter, wenn ich noch etwas raussuchen soll, bitte Bescheid geben

**Comment by hobbyquaker** [comment]
@kwithus bitte teste mal wie es sich mit RedMatic 5.2.2 verhält.

**Comment by kwithus** [comment]
Fast perfekt, danke
Licht an/aus funktioniert, sowohl Anzeige wie auch Steuerung
Garagentor funktioniert auch für offen/geschlossen (Anzeige und Steuerung)
Es fehlt einzig die korrekte Anzeige für Lüftungsposition (dabei öffnet das Tor nur ein kleines Stück), derzeit wird dies als geöffnet dargestellt, sowie die Ansteuerung dieser Position.
Da diese Position als geöffnet angezeigt wird, muss man in Home dann auch zunächst auf schließen gehen und dann erst auf öffnen, wenn man aus der Lüftungsposition öffnen will.
In Homematic wird dies alles getrennt dargestellt und man kann aus der Lüftungsposition direkt öffnen.

**Comment by hobbyquaker** [comment]
> Es fehlt einzig die korrekte Anzeige für Lüftungsposition
@kwithus das lässt sich leider nicht in HomeKit abbilden, die Characteristic kennt leider nur "offen" und "zu".

**Comment by kwithus** [comment]
Das hatte ich schon befürchtet, hatte gehofft, dass es eventuell mit irgendeinem workaround umgangen werden kann (zusätzliches Gerät oder ähnliches)- naja HomeKit ist halt an vielen Stellen sehr beschränkt
