### ISSUE TITLE
Möglich dieses Plugin zu intrigieren?

### ISSUE THREAD

**Issue by LevelOne2k** [rdmtc/RedMatic-HomeKit#207]
Hallo @hobbyquaker 

Wäre es möglich, dieses Plugin mit zu intrigieren?

https://www.npmjs.com/package/homebridge-magichome-platform 

Damit kann man dann jeden LED-Streifen in Verbindung mit diesem Controller über HomeKit steuern:
https://www.amazon.de/Controller-gesteuert-Dynamische-Farbwechsel-Fernbedienung/dp/B0772TB9L4/ref=sr_1_1_sspa?__mk_de_DE=ÅMÅŽÕÑ&crid=212HXW62QBLHS&keywords=led+wifi+controller&qid=1573820956&s=lighting&sprefix=led+wifi%2Clighting%2C179&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExNEZMU1U0MTQwRFlLJmVuY3J5cHRlZElkPUEwOTM4MTQ2N01VQUlVREw4NkxJJmVuY3J5cHRlZEFkSWQ9QTAwNDAxMjczN1oyMkFFUlE1MlJEJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==

Das wäre echt klasse von Dir!

Danke!

**Comment by hobbyquaker** [comment]
Das kannst Du manuell verbinden, mit dem Universal Accessory von RedMatic-HomeKit (https://github.com/rdmtc/RedMatic/wiki/Homekit#universal-accessory) und einem dieser Nodes: https://flows.nodered.org/search?term=magic+home

**Comment by LevelOne2k** [comment]
@hobbyquaker danke für die Antwort. Wie installiere ich die Nodes? Und welche von den 3 müsste ich nehmen? Danke Dir!

**Comment by hobbyquaker** [comment]
Die solltest Du über Node-RED installieren können (siehe https://github.com/rdmtc/RedMatic/wiki/Node-Installation)

Welcher der 3 Nodes am besten taugt (oder ob sie überhaupt was taugen) kann ich Dir nicht sagen, nutze sie nicht ;-) Siehe dazu auch https://github.com/rdmtc/RedMatic/wiki/Node-Installation#kommentar-wie-kann-ich-die-qualit%C3%A4t-von-node-red-nodes-beurteilen

**Comment by LevelOne2k** [comment]
Leider finde ich über die Paletten nichts mit "magichome-led-node"

<img width="450" alt="Bildschirmfoto 2019-11-15 um 19 15 24" src="https://user-images.githubusercontent.com/25386824/68965555-5a746b00-07dc-11ea-894c-5b443b72f6c9.png">

**Comment by LevelOne2k** [comment]
@hobbyquaker Ich habe diesen jetzt installiert: https://flows.nodered.org/node/node-red-contrib-magichome-controller

Aber es scheint nicht zu funktionieren, die LED Leiste taucht nicht in der Home App auf.

Ich habe auch alles eingestellt und die LED Leiste scheint im Node-RED online zu sein.

<img width="450" alt="Bildschirmfoto 2019-11-15 um 19 31 06" src="https://user-images.githubusercontent.com/25386824/68966503-8ee92680-07de-11ea-9863-856dd493cd21.png">

**Comment by Hypnos3** [comment]
Was bedeutet "scheint im Node-RED online zu sein."?
Kannst du die LED Leiste über Node-Red auch direkt schalten? (Inject Node davor, Debug Node dahinter)

Wenn das geht muss du es mit dem Universal Accessory von RedMatic-HomeKit (https://github.com/rdmtc/RedMatic/wiki/Homekit#universal-accessory) dann verbinden. (Da kann ich dir leider nicht helfen.)

**Comment by LevelOne2k** [comment]
Ich blicke da leider nicht durch :-(
