### ISSUE TITLE
[FR] Blacklist for the zigbee node

### ISSUE THREAD

**Issue by bohtho** [rdmtc/RedMatic-HomeKit#215]
I cant find any documentation in the node or on this site for the zigbee node. I read the German wiki as well.

Is it possible to adjust any settings for this node?

Would it be possible to implement sort of a “blacklist” for zigbee devices I *don’t* want over from zigbee-herdsman to HomeKit?

**Comment by hobbyquaker** [comment]
This is already possible, you can uncheck devices in the RedMatic-HomeKit Zigbee Node Configuration. Mind that you have to restart Node-RED after Deploying and that it can take a while until iOS notices that accessories were removed.

**Comment by bohtho** [comment]
True. I was actually thinking of some sort of regex pattern matching for types, manufacturers or parts of the friendly name, but the checkboxes will do for now.
