### ISSUE TITLE
IP Wired 4-fach-Jalousie-/Rollladenaktor HmIPW-DRBL4 fehlt

### ISSUE THREAD

**Issue by peissl-at** [rdmtc/RedMatic-HomeKit#216]
Hallo,

ich finde RedMatic und die HomeKit-Integration echt genial.  
Vielen Dank dafür.

Leider fehlt aber der HmIP Wired 4-fach-Jalousie-/Rollladenaktor 
[HmIPW-DRBL4](https://at.elv.com/homematic-ip-wired-4-fach-jalousie-rollladenaktor-hmipw-drbl4-vde-zertifiziert-152431)
Vielleicht kann er in Zukunft integriert werden.

Sonnige Grüße!
Robert

**Comment by hobbyquaker** [comment]
Danke für das Feedback! Ich schau dass Unterstützung für den DRBL ins nächste Release kommt, hoffe das noch dieses Jahr fertig zu bekommen.

**Comment by peissl-at** [comment]
Danke für die rasche Rückmeldung. Die Umsetzung ist nicht dringend, momentan hält sich die sommerliche Überwärmung leider in Grenzen. 😉 
Zum Usertreffen: Habe ich gerne gemacht, ist ja ein tolles Projekt. Vielleicht bist beim nächsten Mal selbst dabei?

Sonnige Grüße und bis demnächst in Kassel...
Robert

**Comment by hobbyquaker** [comment]
Graz ist selbst aus Süddeutschland ne echte Reise, ich glaub da passe ich :-) Falls ihr mal was in der Gegend um Salzburg macht wär's näher ;-) Aber Kassel hab ich 2020 eingeplant.

**Comment by peissl-at** [comment]
Kein Thema, dann bis spätestens in Kassel!

**Comment by Bugi66** [comment]
Hallo,

gibt es schon einen Zeitplan für die Umsetzung?

Ansonsten ist es die wohl einfachste Möglichkeit Home-Kit zu nutzen.
Sehr geiles Projekt, vielen Dank für die bisher geleitete Arbeit

Grüße aus Falkensee...
Bugi

**Comment by hobbyquaker** [comment]
@peissl-at Der DRBL4 ist in RedMatic 5.3.0 implementiert, allerdings im Blindflug (habe dieses Gerät nicht). Bitte gib Bescheid ob es funktioniert.

**Comment by peissl-at** [comment]
Hallo hobbyquaker,

zuerst mal: Ein gutes neues Jahr!

Und ja, die Implementierung des DRBL4 funktioniert. Super, danke! 

Inzwischen hab ich weitere HmIPW-Geräte installiert (DRI32, DRS8 und SMI55). Dabei sind mir noch zwei Schönheitsfehler aufgefallen, die auf sämtliche HmIP-Wired Geräte zutreffen: 

- alle HmIPW- Geräte werden im HomeKit nur als SingleAccessory angezeigt. Auch wenn das Häckchen im RedMatic nicht gesetzt ist. Bei den alten HM-Wired-Geräten funktioniert das korrekt. Dadurch können alle Kanäle eines Gerätes leider nur einem Raum zugeordnet werden.

- der erste Kanal des HmIP-Wired Kanal wird unterdrückt. Das passt beim DRBL4 und beim DRS8 so, weil da sind es nur Status-Kanäle. Beim DRI32 fehlt dadurch aber der erste Eingangskontakt.

Das SMI55 fehlt noch zur Gänze. Hier die Datenpunkte, falls Du es mal integrieren möchtest:
HmIPW-SMI55:0 -> Gerätestatus = irrelevant
HmIPW-SMI55:1 -> Taste unten = irrelevant
HmIPW-SMI55:2 -> Taste oben  = irrelevant
HmIPW-SMI55:3 -> Bewegungsmelder = wichtig
          CURRENT_ILLUMINATION
          CURRENT_ILLUMINATION_STATUS
          ILLUMINATION
          ILLUMINATION_STATUS
          MOTION
HmIPW-SMI55:4 -> Unterdrückung der Bewegungserkennung = irrelevant

Ich hab auch noch ein HmIPW-FIO6 da liegen, eventuell schaffe ich es in den kommenden Tagen das Teil zu verbauen, dann kann ich dir auch diese Datenpunkte listen, wenn du möchtest.

Generell finde ich deine HomeKit-Integration sehr gelungen. Sogar die Erreichbarkeit und die Batterien sind bestens integriert. Damit RedMatic mit HomeKit zu meiner Standard-Bedienung geworden. Super, vielen Dank! 

Damit gibt es am nächsten Homematic-Usertreffen sicher einen ausführlicheren Vortrag!

Sonnige Grüße!
Robert

**Comment by hobbyquaker** [comment]
Ref HmIPW-SMI55: #237

**Comment by hobbyquaker** [comment]
Ref HmIPW-DRI32: #238

**Comment by hobbyquaker** [comment]
Ref HmIPW-FIO6: #239

**Comment by hobbyquaker** [comment]
Ref SingleAccessory: #240
