### ISSUE TITLE
1. Bridge ist nach hinzufügen einer 2. Bridge nicht mehr verfügbar bzw. Geräte "keine Antwort"

### ISSUE THREAD

**Issue by TheRealTremes** [rdmtc/RedMatic-HomeKit#217]
Hallo, ich habe RedMatic mit der Homebridge nun schon lange wunderbar und ausfallsicher im Einsatz.

Ich wollte nun auch meine Harmony über HomeKit steuern. Ich habe also den Harmony Node installiert, dann einen neuen Flow angelegt und dort von links bei "RedMatic HomeKit" einen neuen "homematic" hineingezogen. Doppelklick auf diesen, dann "Neuen redmatic-homekit-bride" angeklickt. Bei "Bridge Name" habe ich "Harmony RM Bridge" eingetragen. Dann auf hinzufügen geklickt und die neue Bridge war hinzugefügt. Der QR-Code wurde mir auch angezeigt und konnte die neue auch Bridge in der Home App hinzufügen und dort dann meine Harmony Aktivitäten steuern. Im neuen Flow in dem neuen homematic Node habe ich die neue Bridge ausgewählt und alle CCU Geräte deaktiviert.

Nun, seitdem ich die 2. Bridge hinzugefügt habe, steht bei der "CCU" Bridge bei den Geräte "Keine Antwort" In meinem CCU Flow ist beim homematic Node die alte Bridge ausgewählt und auch die CCU Geräte.

Deploy habe ich natürlich gemacht und auch die gesamte RedMatic neu gestartet, leider ohne erfolg. Wenn ich die 2. neue Bridge die ich für den Harmony Node nutzen möchte wieder lösche, dann funktioniert die 1. Bridge wieder wunderbar und alle Geräte darin auch.

Funktioniert das ganze nicht wenn man mehrere Bridges haben möchte, oder habe ich etwas falsch gemacht?

Edit: Ich habe der 2. Bridge mal einen anderen Port gegeben (51827) Die 1. Bridge hat den Port 51826. Jetzt läuft beides. Die 1. Bridge ist wieder Verbunden bzw. alle Geräte an dieser funktionieren und die 2. Bridge mit dem Harmony Node und den Harmony Aktivitäten funktioniert auch. Hat es daran gelegen, dass beim ersten Mal einrichten beide Bridges denselben Port hatten?

**Comment by hobbyquaker** [comment]
Ja, wenn beide den gleichen Port verwenden funktioniert es nicht. Werde mal schauen ob es eine Möglichkeit gibt das zu erkennen und eine Fehlermeldung auszugeben.

**Comment by TheRealTremes** [comment]
Ah super. Jetzt habe ich schon meine 3. HomeBridge erfolgreich am laufen, alle unter einem anderen Port. Danke sehr!
