### ISSUE TITLE
HmIP-FCI1 als Doorbell Accessory

### ISSUE THREAD

**Issue by klingbing** [rdmtc/RedMatic-HomeKit#219]
Hallo,

es gibt ja mitlerweile einige Doorbell Issues  #30, #125, #198, #214, hier nun ein weiterer:   

Ich plane ein Setup mit einer Kombination aus Ubiquiti UniFi Protect G3 Flex Kamera, einem HmIP-SMO Bewegungsmelder und einem mit der Türklingel verbundenem HmIP-FCI1.
Wäre es in diesem Zusammenhang möglich, letzterem auch den Typ Doorbell zuzuweisen? Ich weiss, es ginge auch über das Universal Accessory, aber das Anwendungsszenario HmIP-FCI1 an der Türklingel ist so naheliegend, dass ich hoffe, dass diese Verbesserung auch (irgendwann!) berücksichtigt werden kann.

Wie immer, danke für deinen Einsatz und deine Arbeit an Redmatic!

**Comment by hobbyquaker** [comment]
Die Kamera unterstützt nun auch den Doorbell Service, siehe https://github.com/rdmtc/RedMatic-HomeKit/issues/198#issuecomment-570273593
Um den FCI1 dafür zu nutzen kannst Du ein RPC Event Node mit Regex Filter auf Datapoint `PRESS_.*` mit dem Eingang des Kamera Nodes verbinden.
