### ISSUE TITLE
Add allowInsecureRequest option on bridge

### ISSUE THREAD

**Issue by bohtho** [rdmtc/RedMatic-HomeKit#220]
If the bridge would implement the option to allowInsecureRequest (as is possible in Homebridge and some other HAP-nodejs implementations), it would be possible to play more with the HomeKit devices in Node-RED (especially by pointing node-red-contrib-homebridge-automation at the devices automatically added to HomeKit by the RedMatic-HomeKit Zigbee node).

**Comment by hobbyquaker** [comment]
Is implemented in 3.0.0-beta.0
Please give me feedback if it's working for you

**Comment by bohtho** [comment]
Seems to work ! I can get access to the devices from Homebridge as well etc.
