### ISSUE TITLE
Räume mit Umlauten

### ISSUE THREAD

**Issue by Feldman01** [rdmtc/RedMatic-HomeKit#226]
Hallo Zusammen,
ich steuere meine Jalousien über Redmatic-Homekit und alles funktioniert sehr gut. Sobald ich jedoch Siri bitte eine Jalousie in einen Raum mit einen Umlaut auf z.B. Küche 20% zu stellen, stellt sie alle Räume auf 20%. Auch den Raum in Kueche umzubenennen, oder neu anzulegen hilft nicht.  Denke es liegt an der Bridge, denn vorher hatte ich mit Homebridge gearbeitet und da ist dies nicht aufgetreten

Vielen Dank schon mal

**Comment by hobbyquaker** [comment]
Das das an der Bridge hängt halte ich für eher ausgeschlossen, die Bridge kennt weder Räume noch ihre Namen, die existieren ausschließlich in iOS. Möglicherweise hängt es aber mit der Benennung der Geräte selbst zusammen, hattest Du mit der Homebridge evtl. andere Namen vergeben?

**Comment by Feldman01** [comment]
Hi,
die Geräte heißen in der Ccu3 z.B. Rollo Küche. In HomeKit heißt es nur Rollo und ist der Küche zugeordnet. Das funktioniert mit jedem Raum, nur die mit Umlauten steuern dann alle Rollos, zumindest wenn mal es mit Siri steuert. Das hat mit Homebridge funktioniert. Eventuell liegt es aber auch an einem iOS Update. Sobald ich das Rollo in Rollo Küche ändere, geht es 🤷‍♂️. Jetzt ein neues Problem. Habe heute das neue Redmatic Updaten gemacht und alle Favoriten in Homekit zeigen keine Verbindung an. Erst wenn mach auf das Gerät drauf drückt, wird es verbunden??

**Comment by hobbyquaker** [comment]
>  Habe heute das neue Redmatic Updaten gemacht und alle Favoriten in Homekit zeigen keine Verbindung an. 

Wenn das passiert empfehle ich folgendes vorgehen:
* Wifi am iOS Gerät deaktivieren
* Home.app öffnen
* Home.app "abschießen" (nach oben rauswischen)
* Wifi am iOS Gerät wieder aktivieren
* 2 minuten warten

**Comment by Feldman01** [comment]
Hilft leider nichts 🤷‍♂️

**Comment by hobbyquaker** [comment]
Das mit dem "keine Antwort" war ein Bug der mit RedMatic 5.3.8 gelöst ist (#246).

**Comment by Feldman01** [comment]
Hi,
Update durchgeführt, geht leider immer noch nicht 🤷‍♂️

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/RedMatic-HomeKit/issues/246#issuecomment-571275545
