### ISSUE TITLE
RedMatic-(HomeKit) neu starten per URL möglich?

### ISSUE THREAD

**Issue by TheRealTremes** [rdmtc/RedMatic-HomeKit#228]
Hallo, ich steuere über RedMatic HomeKit u.a. meinen AVR-Receiver. Wenn hier alles ausgeschaltet ist, dann wird den Geräten per Zwischenstecker auch der Strom entzogen, auch dem AVR-Receiver. Dadurch das der AVR-Receiver keinen Strom mehr hat, meldet der Node immer das er den AVR-Receiver nicht erreicht, was ja erstmal normal ist und mich nicht stört. Wenn ich nun alles einschaltet und der AVR-Receiver auch wieder Strom hat, dann dauert es knapp 10 Minuten bis ich ihn über HomeKit wieder steuern kann, wahrscheinlich benötigt der Node dann diese Zeit um die Verbindung zum AVR-Receiver wiederherzustellen. Wenn ich nun die RedMatic neu starte, dann kann ich den AVR-Receiver nach dem neu start von RedMatic wieder sofort bedienen und muss nicht die 10 Minuten warten. Daher kam mir der Gedanke, dass ich die RedMatic per URL neu starte damit ich nicht die 10 Minuten warten muss bis ich den AVR-Receiver steuern kann. Z.B. per Programm --> Wenn Zwischenstecker ein, dann Script mit URL um RedMatic neu zu starten.

Ist es möglich RedMatic per URL neu zu starten? Oder gibt es sogar eine bessere Lösung z.B. den Node neu starten sobald der AVR-Receiver wieder Strom hat.

Danke!

**Comment by LevelOne2k** [comment]
Das würde mich auch interessieren.

@hobbyquaker Wie wird denn über diesen Button ein Neustart angestoßen? Vielleicht kann man daraus etwas stricken.
<img width="123" alt="Bildschirmfoto 2019-12-22 um 14 47 40" src="https://user-images.githubusercontent.com/25386824/71322638-3c301800-24ca-11ea-8ee9-ffef7b0e98da.png">

**Comment by hobbyquaker** [comment]
Auf der Shell: `/etc/config/rc.d/redmatic restart`
Der API Endpunkt für das UI benötigt eine Rega-Session, daher eher ungeeignet.

**Comment by LevelOne2k** [comment]
Super, funktioniert wunderbar per CCU Programm und Script mit Inhalt

```
string cmd = "/etc/config/rc.d/redmatic restart";
system.Exec(cmd, &stdout, &stderr);
```
