### ISSUE TITLE
Geräteliste im RedMatic HomeKit - Homematic Node aktualisiert sich nicht

### ISSUE THREAD

**Issue by rost2802** [rdmtc/RedMatic-HomeKit#232]
Hallo,

gibt es eine Möglichkeit die Geräteliste im RedMatic HomeKit - Homematic Node manuell zu aktualisieren? Änderungen in der WebUI erscheinen nicht in der Liste.

Vielen Dank.

**Comment by hobbyquaker** [comment]
Einfach Node-Red neustarten. Könnte auch reichen nur die Flows neuzustarten.

**Comment by rost2802** [comment]
Danke für die Antwort und noch frohe Weihnachten!

Hab schon alles mögliche neu gestartet:
RedMatic und CCU3

Erst nach einer kompletten Neuinstallation von RedMatic aktualisiert sich die Liste.

**Comment by hobbyquaker** [comment]
Hmm, kann ich nicht reproduzieren, bei mir ist nach Flow oder Node-RED Neustart alles aktuell. Wenn das bei Dir nicht klappt könnte das ein Bug sein, dann bräuchte ich mal ein Log auf Debug Level.

**Comment by rost2802** [comment]
[redmatic.2019-12-26T12_11_57.393Z.log](https://github.com/rdmtc/RedMatic-HomeKit/files/4002496/redmatic.2019-12-26T12_11_57.393Z.log)

**Comment by rost2802** [comment]
Zwischeninfo... Neue Geräte werden angezeigt.
Nur Änderungen an Namen (Homematic) oder Änderungen des Typs (CUxD) nicht.

**Comment by rost2802** [comment]
Ich geb nicht auf...
Änderungen des Gerätetyps (CUxD) funktionieren wenn:

1. RedMatic Stoppen
2. Gerät aus CCU löschen mit Werkseinstellungen
3. RedMatic Starten
4. Homekit Node öffnen (Gerät ist aus der Liste weg)
5. Das Fehlen des Geräts mit Fertig und deploy bestätigen
6. RedMatic stoppen
7. In CUxD Gerät mit anderem Gerätetyp erstellen (bekommt selbe Seriennummer)
8. CCU Posteingang Einstellungen tätigen
9. RedMatic Starten
10. Homekit Node öffnen und über das geänderte Gerät freuen ;-)

Ist das verhalten normal?
Für die Änderung der Homematic Namen hab ich noch keine Lösung...

**Comment by jpawlowski** [comment]
Ich habe das Phänomen auch auf zwei Systemen.

**Comment by hobbyquaker** [comment]
Hmm, ich kann das nicht reproduzieren, bei mir funktioniert die Umbenennung einwandfrei:
![rename mov](https://user-images.githubusercontent.com/2503307/71526869-1b583000-28d9-11ea-99ff-5233be20fc3d.gif)

Könnt Ihr mir mal genau auflisten wie ihr beim Umbenennen vorgeht?

Das mit dem geänderten Gerätetyp beim CUxD leuchtet ein (eine Änderung des Gerätetyps ist auf der Homematic XML RPC Schnittstelle nicht vorgesehen, das ist ein CUxD-Sonderfall)

Es sollte aber folgendes Vorgehen reichen um eine Änderung des Typs zu übernehmen:
* Node-RED stoppen
* Auf CCU die Datei `/usr/local/addons/redmatic/var/ccu_localhost.json` löschen
* Node-RED starten

**Comment by hobbyquaker** [comment]
Jetzt kam mir noch was: Meint Ihr die Umbennenung greift nicht in HomeKit, also in der Home.app/Siri? Falls ja - das ist leider so. Ich kann einem Gerät nur initial beim Pairing einen Namen mitgeben, der wird von iOS dann so gespeichert. Nachträglich den Namen ändern geht nur aus iOS selbst heraus, das kann die Bridge prinzipbedingt nicht (genauso wie die Bridge z.B. auch kein Einfluss auf Raumzuweisungen hat, die existieren nur in iOS).

**Comment by rost2802** [comment]
Jetzt habe ich bestimmt 5x RedMatic komplett neu aufgesetzt um Änderungen zu bekommen... und nun Funktioniert es beim Testen nach dem Video direkt beim ersten mal ohne Probleme. Vielen Dank für die Info mit der zu löschenden Datei bei CUxD Geräten. Sowas hatte ich erfolglos gesucht. Also letztendlich alle Klarheiten beseitigt. Vielen Dank und einen Guten Rutsch!

**Comment by jpawlowski** [comment]
Ich hätte wohl spezifischer sein sollen. Ich habe zwei seltsame Verhalten, die so klangen, als wären sie hiermit im Zusammenhang. Da das Thema wohl nun gerade nicht mehr relevant ist, schreibe ich das mal in zwei neue Issues.

**Comment by hobbyquaker** [comment]
Dann kann ich hier schließen?

**Comment by rost2802** [comment]
Von mir aus ja... hier funktioniert jetzt alles bestens. Danke
