### ISSUE TITLE
Tasterkanal von HMW-IO-12-Sw7-DR direkt in HomeKit einbinden?

### ISSUE THREAD

**Issue by Hoefti1980** [rdmtc/RedMatic-HomeKit#235]
Hallo,

wäre es möglich meine Tasterkanäle  von dem Wired Modul HMW-IO-12-Sw7-DR auch in der HomeKit App anzuzeigen?
Ich bekomme es mit Node Red irgendwie nicht hin :-(.  Ich habe es mit RAS Event und auch schon mit einer Systemvariable probiert.
Ich möchte gerne das meine HomePods bei Klingelbetätigung direkt einen Sound abspielen.
Die Klingel ist an dem Tasterkanal der HMW-IO-12-Sw7-DR angeschlossen, der wird ja aber nicht direkt in der HomeKit App angezeigt, so das ich den direkt einbinden kann.

Das mit der Systemvariable funktioniert zwar, ist aber stark zeitverzögert.

Vielleicht gibt es ja auch noch eine andere Lösung, ich bin für jede Hilfe dankbar :-).

Gruß
Hoefti1980

**Comment by hobbyquaker** [comment]
Siehe https://github.com/rdmtc/RedMatic/wiki/Homekit#tasten

**Comment by Hoefti1980** [comment]
Guten Morgen,

habe ich auch schon probiert, bei meinem Funktaster funktioniert es auch, bei dem Wired Modul leider nicht.
Ich habe mal ein Bild von der Einstellung angehängt.

Gruß
Arne

![Bildschirmfoto 2019-12-29 um 09 46 35](https://user-images.githubusercontent.com/51029566/71554541-dd662380-2a20-11ea-8ba7-6e7d25044c37.png)

**Comment by hobbyquaker** [comment]
Häng mal ein Debug Node an den Ausgang des RPC Event Nodes und schau ob/was da für eine Nachricht rauskommt wenn Du eine Taste drückst.

**Comment by KPfundstein** [comment]
Hallo, wenn ich mich nicht ganz arg täusche, dann giebt es bei dem Sensor kein press_long bzw. press_short, sondern nur ein offen und geschlossen, denn das ist kein Taster sondern ein sensor  ....

**Comment by hobbyquaker** [comment]
Doch, der 12/7 hat PRESS_SHORT/LONG Datenpunkte, die Eingänge sind nur für Taster geeignet. Nur beim 12/14 ist das anders.

**Comment by Hoefti1980** [comment]
Wenn ich den Taster drücke steht im Debug Node true.
Wenn ich den Taster in der HomeKit App zuordne passiert weiterhin nichts.

Gruß
Arne

![Bildschirmfoto 2019-12-29 um 19 53 41](https://user-images.githubusercontent.com/51029566/71561301-044e4500-2a75-11ea-8fe0-73865aa32518.png)

**Comment by hobbyquaker** [comment]
Hast Du das richtige Topic im RPC Event Node konfiguriert?

**Comment by Hoefti1980** [comment]
Passt auch, verstehe nicht warum es bei den Funktaster funktioniert, oder ich bin einfach zu blöd ;-).
![Bildschirmfoto 2019-12-29 um 20 21 11](https://user-images.githubusercontent.com/51029566/71561626-2d70d480-2a79-11ea-919b-48b101ef6683.png)

**Comment by hobbyquaker** [comment]
Ist der Node mit dem Namen "Klingel" auf Deinem Screenshot der der nicht funktioniert? Falls ja - ist das überhaupt ein "RedMatic-HomeKit Event" Node? 
Wenn das kein "Event" Node sondern ein "Universal Accessory" Node ist passt der Payload nicht, da müsstest dann mit einem Change Node erst den Payload passend setzen. 
Sollte es ein "Event" Node sein dann exportier mal bitte die beiden Nodes und paste das JSON hier.

**Comment by Hoefti1980** [comment]
Das ist ein Event Node, genau wie beim Funktaster.
Auf dem 2ten Bild ist die Meldung von dem Node.

![Bildschirmfoto 2019-12-29 um 20 36 26](https://user-images.githubusercontent.com/51029566/71561822-12539400-2a7c-11ea-8a6a-5f460a5f919f.png)
![Bildschirmfoto 2019-12-29 um 20 43 54](https://user-images.githubusercontent.com/51029566/71561830-27c8be00-2a7c-11ea-90c3-9335adac358b.png)

**Comment by hobbyquaker** [comment]
ah, ja jetzt is klar. Der RPC Event Node gibt als Topic aus `12/PRESS_SHORT`. Der HomeKit Event Node erwartet aber 1/PRESS_SHORT. Änder mal die Topic Konfiguration im RPC Event Node auf `1/${datapoint}`, dann sollte es gehen. Hintergrund des ganzen ist dass man mit einem einzigen Päärchen aus RPC Event und HomeKit Event mehrere Tasten sowohl mit PRESS_SHORT als auch PRESS_LONG abdecken kann (auf deinem Screenshot ist z.B. für Schlafzimmer SHORT/LONG zweimal vorhanden, das würde mit passender Topic-Konfiguration auch einmal für beides reichen...)

**Comment by Hoefti1980** [comment]
Das war's :-).
Vielen vielen Dank mal wieder!
Kann ich hier eigentlich auch eine Spende hinterlassen so wie in der CCU?
Ich bin Euch echt dankbar für den super Support, vor allem ist es echt cool für Leute wie mich die Anfänger sind.

Gruß
Arne

**Comment by hobbyquaker** [comment]
Spende - das ist lieb - aber nein :-)
Zum Thema Spenden und warum ich keine Spenden annehme hab ich hier mal was geschrieben: https://github.com/rdmtc/RedMatic/wiki/Faq#wie-kann-ich-mich-erkenntlich-zeigen
