### ISSUE TITLE
TemperatureSensor: Negative Werte immer gleich 0

### ISSUE THREAD

**Issue by superpower10** [rdmtc/RedMatic-HomeKit#236]
Ich berechne die gefühlte Temperatur und liefere diese an einen Universal-Knoten. Dort setze ich den Wert in 0/TemperatureSensor.

Das funktioniert bei positiven Temperaturen immer einwandfrei.

Sobald der Wert negativ wird, kommt in HomeKit immer 0 Grad an.

Es wird aber definitiv ein negativer Wert an den Knoten geliefert (siehe Screenshot):
<img width="494" alt="Bildschirmfoto 2019-12-29 um 17 57 41" src="https://user-images.githubusercontent.com/20533966/71560013-b8939f80-2a64-11ea-8cd1-7d87fcf1fd98.png">

**Comment by hobbyquaker** [comment]
Siehe https://github.com/rdmtc/RedMatic-HomeKit/issues/111#issuecomment-455775364

**Comment by superpower10** [comment]
Habe ich wie folgt gemacht. Leider kommt dann eine Fehlermeldung:
<img width="511" alt="Bildschirmfoto 2019-12-29 um 22 52 55" src="https://user-images.githubusercontent.com/20533966/71563325-17214380-2a8e-11ea-9939-808661b55b05.png">
<img width="514" alt="Bildschirmfoto 2019-12-29 um 22 53 01" src="https://user-images.githubusercontent.com/20533966/71563326-1ab4ca80-2a8e-11ea-9669-b7f4a8b01ec2.png">
<img width="321" alt="Bildschirmfoto 2019-12-29 um 22 53 33" src="https://user-images.githubusercontent.com/20533966/71563327-1c7e8e00-2a8e-11ea-8283-fc8f395db559.png">

**Comment by superpower10** [comment]
Funktioniert leider nicht.

Habe es wie folgt gemacht:
<img width="514" alt="Bildschirmfoto 2019-12-29 um 22 53 01" src="https://user-images.githubusercontent.com/20533966/71563393-ef7eab00-2a8e-11ea-8923-2e83419ba63f.png">
<img width="510" alt="Bildschirmfoto 2019-12-29 um 22 59 05" src="https://user-images.githubusercontent.com/20533966/71563395-f3123200-2a8e-11ea-81b8-1ef823f365c9.png">

**Comment by superpower10** [comment]
Kommando zurück. Jetzt geht’s 👏🏻👏🏻👏🏻
