### ISSUE TITLE
HmIPW-DRI32 first channel missing

### ISSUE THREAD

**Issue by hobbyquaker** [rdmtc/RedMatic-HomeKit#238]

**Comment by peissl-at** [comment]
Guten Morgen hobbyquaker,

habe gerade eben auf die Version 5.3.3 upgedatet. Der erste Kanal wird im Homematic-Flow nun auch zur Auswahl gelistet.
Aber da am iPad die Geräte noch an einen einzigen Raum gebunden waren, habe ich sie im Homekit-Node deaktiviert und RedMatic neu gestartet. Nachdem die Geräte am iPad nicht mehr angezeigt wurden, hab ich im Homekit-Node wieder angewählt und deployed.
Trotz mehreren Versuchen erscheinen sie am iPad (auch iPhone und MacBook) nicht mehr.
Selbiges Problem hab ich jetzt beim HmIPW-DRS8.

Was kann ich noch versuchen?

Sonnige Grüße!
Robert
