### ISSUE TITLE
noch immer Problem mit SingleAccessory beim HmIPW-DRBL4

### ISSUE THREAD

**Issue by peissl-at** [rdmtc/RedMatic-HomeKit#243]
Hallo, 

das letzte Issue wurde inzwischen geschlossen. Ich denke, der Bug wurde aber leider nicht zur Gänze behoben.

Seit dem letzten Update auf 5.3.3 ist der Menüpunkt "SingleAccessory" beim HmIPW-DRBL4 nicht mehr in Homekot-Flow enthalten.
<img width="567" alt="Bildschirmfoto 2020-01-03 um 10 28 53" src="https://user-images.githubusercontent.com/58342709/71716142-02d5a180-2e14-11ea-8a86-ecf9097e0965.png">

Aber die 4 Kanäle werden noch immer als ein Gerät in der HomeKit App angezeigt. (Hab auch das Gerät im Homekir-Flow deaktiviert und RedMatic neu gestartet - alles leider ohne Erfolg)

Die Darstellung hat sich zwar verändert. Schaut jetzt cool aus, sollte aber trotzdem in unterschiedlichen Räumen verwendbar sein.
<img width="170" alt="Bildschirmfoto 2020-01-03 um 10 33 18" src="https://user-images.githubusercontent.com/58342709/71716290-7d9ebc80-2e14-11ea-9dc2-4fd0b59db62c.png">

Sonnige Grüße!
Robert

**Comment by hobbyquaker** [comment]
Hoffe das mit RedMatic 5.3.4 behoben zu haben. Bitte geb Bescheid ob es passt.

**Comment by peissl-at** [comment]
bitte siehe #242

**Comment by Schochi** [comment]
Ist bei 5.3.4 auch noch so

**Comment by hobbyquaker** [comment]
Ich hab beim DRBL4 aus "Faulheit" die SingleAccessory Checkbox weggelassen, der soll default für die 4 Rollläden 4 einzelne Accessories anlegen (so dass die auch verschiedenen Räumen zugeordnet werden können). Könnt ihr das noch mal prüfen? Falls das nicht der Fall ist bräuchte ich mal ein Log auf Debug Level dass den Node-RED Start beinhaltet.

**Comment by Schochi** [comment]
[log.zip](https://github.com/rdmtc/RedMatic-HomeKit/files/4020923/log.zip)
Logfile ist anbei . danke!!!

**Comment by peissl-at** [comment]
Fehler in der 5.3.5 leider noch vorhanden. Wenn ein zweites Logfile benötigt wird, bitte melden...

**Comment by hobbyquaker** [comment]
Ich glaube ich hab das Problem gefunden, bin verhalten optimistisch dass es mit RedMatic 5.3.6 gelöst ist. Bitte gebt Bescheid ob es passt.

**Comment by Schochi** [comment]
Schaut gut aus was ich auf den ersten Blick erkennen kann. Bin gerade unterwegs - teste es morgen ausführlich. 
Tausend dank! 

![AB346CB1-217A-449D-ADC2-D9417BE5F5BE](https://user-images.githubusercontent.com/51194173/71769046-62b76f80-2f1c-11ea-80f5-0e0fd91c90ae.png)

**Comment by peissl-at** [comment]
Hallo,
ich bin momentan unterwegs und kann daher erst morgen testen. Aber im Screenshot von Schochi sieht man sehr viele Icons. Sind da möglicherweise auch die virtuellen Kanäle integriert worden? Das wäre dann etwas zuviel des Guten. 😉
Sonnige Grüße!
Robert

**Comment by hobbyquaker** [comment]
Virtuelle Kanäle werden unterstützt, sind aber default nicht aktiviert. 
Ich persönlich finde das auch überflüssig die virtuellen Kanäle in HomeKit abzubilden, aber einige User wünschen sich das sehr, das Thema ist auch schon mal ziemlich hochgekocht: #157

**Comment by peissl-at** [comment]
Sorry, hab 168 Geräte und dachte nicht, dass sich jemand die Ansicht freiwillig zupflastert 😉
Hab gerade eben auf die 3.5.6 upgedatet und die Ansicht wurde korrigiert, ohne das ich das Gerät im Homekit Flow ab- und wieder anwählen musste! PERFEKT!
Info zum FIO6 folgt...
