### ISSUE TITLE
Geräte stehen nach RedMatic Update auf "Keine Antwort" lassen sich aber bedienen

### ISSUE THREAD

**Issue by LevelOne2k** [rdmtc/RedMatic-HomeKit#246]
Hallo,

ich habe gestern RedMatic und somit auch RedMatic-HomeKit auf die aktuelle Version upgedatet. Seitdem stehen die Geräte in der HomeApp auf "Keine Antwort" ich kann sie jedoch bedienen und danach ist die Meldung "Keine Antwort" auch verschwunden.

Ein RedMatic Neustart hat leider keine Abhilfe geschaffen.

Das komische, die Meldung erscheint nur in der Home App. Egal ob iOS, iPadOS oder macOS. In der Eve App oder der MyHome App bekomme ich keine "Fehlermeldungen".

Ich hatte das Problem bisher noch nie und ich setzte die RedMatic für HomeKit jetzt schon lange ein.

**Comment by peissl-at** [comment]
Hallo, 

ich habe leider das gleiche Problem.

Sonnige Grüße!
Robert

PS: gibt es im Homekit eigentlich eine Limitierung der Anzahl der Geräte?
![IMG_3510](https://user-images.githubusercontent.com/58342709/71783977-84812700-2fee-11ea-8efe-198549a3971a.jpeg)

**Comment by hobbyquaker** [comment]
Wenn man die Geräte dann bedient hat und die Meldung verschwunden ist - kommt sie dann irgendwann wieder oder ist sie dann dauerthaft weg?

**Comment by hobbyquaker** [comment]
> PS: gibt es im Homekit eigentlich eine Limitierung der Anzahl der Geräte?

150 Accessories je Bridge, wenn das nicht ausreicht kann man aber beliebig viele Bridges anlegen und die Geräte auf diese Verteilen (dabei ist zu beachten dass jede Bridge ein individuellen Port konfiguriert haben muss).

**Comment by peissl-at** [comment]
Zu 1: Die Fehlermeldungen sind dann weg, bis RedMatic oder HomeKit-App neu gestartet wird. Es reicht aber auch, wenn man das Gerät nur öffnet (lange drauf tippen), damit "Keine Antwort" verschwindet.
Erweiterte Fehlerbeschreibung: Wenn man durch die Räume wischt, sind in einigen Räume alle Geräte verbunden in einigen Räumen zeigen alle "Keine Antwort". Das ändert sich auch nicht, wenn man mehrmals hin und her blättert. Erst durch obige Maßnahme wird es behoben. 
Wirkt irgendwie, wenn die Antwort von RedMatic zu lange dauert und die HomeKit-App einen Timeout annimmt und durch das einzelne Anwählen wird das Gerät neu gecheckt. Daher hatte ich die Bedenken wegen der maximalen Geräteanzahl.

Zu 2: Super, danke für die Info!

**Comment by hobbyquaker** [comment]
@peissl-at Könntest Du mir mal ein Debug Log zukommen lassen (hobbyquaker@gmail.com, aber bitte Bescheid geben wenn Du eine Mail geschickt hast)? Das Log sollte idealerweise eine Node-RED Neustart beinhalten und das reproduzieren des Fehlers (ein Gerät öffnen damit Fehlermeldung verschwindet, Home.app neu starten damit sie wieder da ist). Super wäre es wenn Du noch die genauen Zeitpunkte notierst wann Du die Fehlermeldung hast verschwinden lassen und wann Du die Home.app dann erneut geöffnet hast.

**Comment by peissl-at** [comment]
Mail mit Logfile und Zeitprotokoll ist gerade raus.

**Comment by hobbyquaker** [comment]
Hmm... Auf den ersten Blick sieht das unauffällig aus, bin noch ziemlich ratlos was da schief geht... :/ Ich befürchte da müssen wir so ein bisschen nach dem Ausschlußverfahren vorgehen. Mit RedMatic-HomeKit 3.0.0 habe ich ein Major Update der zugrundeliegenden HomeKit-Library gemacht ("HAP-Nodejs"), ich würde jetzt als erstes mal gerne versuchen die wieder downzugraden um auszuschließen dass es damit zusammenhängt. Dazu müsstest Dich per SSH auf der CCU einloggen und folgende Kommandos ausführen:

```
source /usr/local/addons/redmatic/home/.profile 
cd /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/
npm install hap-nodejs@0.4.52
/etc/config/rc.d/redmatic restart
```

**Comment by LevelOne2k** [comment]
Ich habe RaspberryMatic installiert. Kann ich das Kommando damit auch nutzen?

**Comment by hobbyquaker** [comment]
Jap, funktioniert genauso auf RaspberryMatic

**Comment by LevelOne2k** [comment]
Beim dritten Schritt kommen Fehler:

![A8E97E8E-1170-4D56-B518-1E15811202F4](https://user-images.githubusercontent.com/25386824/71785269-f876fb80-2ffd-11ea-9442-ab96c2babb4a.png)

**Comment by peissl-at** [comment]
Hallo Sebastian,

DONE…

# source /usr/local/addons/redmatic/home/.profile 
# cd /usr/local/addons/redmatic/lib/node_modules/redmatic-homekit/
# npm install hap-nodejs@0.4.52
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN redmatic-homekit@3.0.2 No repository field.

+ hap-nodejs@0.4.52
updated 1 package and audited 212 packages in 9.772s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

# /etc/config/rc.d/redmatic restart
Stopping Node-RED: OK
Starting Node-RED: OK
# 

…und es schaut gut! 👍 Ich habe keine „Keine Antwort“ mehr.

Aber bitte bedenke, das ist mein Produktiv-System 😉

Sonnige Grüße!
Robert

**Comment by LevelOne2k** [comment]
So, direkt am Mac hat der Downgrade jetzt auch geklappt. Und auch bei mir, ich bekomme keine "Keine Antwort" Meldung mehr, alles gut.

**Comment by hobbyquaker** [comment]
Ok, das ist bemerkenswert. Im HAP-Nodejs Issue Tracker hat bisher niemand so ein Problem gemeldet, das Release ist auch scho 3 Wochen alt 🤔 Ist aber leider mittel/langfristig keine Lösung da auf die alte Version zurückzugehen, den Fehler muss ich noch finden. Ich denke der nächste Schritt wird sein da das Logging noch gesprächiger zu machen und Debug-Meldungen von HAP-Nodejs durchzureichen und mitzuloggen. Werde das mit dem nächsten Release angehen. Da ich das selbst bisher nicht reproduzieren konnte werde ich da noch mal auf eure Mithilfe angewiesen sein, hoffe ich komm nächstes Wochenende dazu. Bis dahin bleibt für die von diesem Bug betroffenen nur der Workaround mit dem manuellen Downgrade...

**Comment by peissl-at** [comment]
Alles klar, dann warte ich auf weitere Instruktionen. Schöne Woche!

**Comment by ThomasRi333** [comment]
The same for "Homekit-Cameras"; with the old Version is everything OK

**Comment by hobbyquaker** [comment]
Hab mich jetzt doch entschieden vorerst hap-nodejs wieder downzugraden, RedMatic 5.3.8 ist in der Mache. Wenn ihr im Moment auf 5.3.7 mit manuellem hap-nodejs Downgrade seid könnt ihr also die 5.3.8 überspringen.

**Comment by tomSmartHome** [comment]
Must be under some specific circumstances as I am a heavy user of the homekit integration and have no issues on 5.3.7.

**Comment by hobbyquaker** [comment]
Is indeed so, I wasn't able to reproduce it on 3 different systems.

**Comment by hobbyquaker** [comment]
FYI: https://homematic-forum.de/forum/viewtopic.php?f=77&t=55766&p=554128#p554128

**Comment by hobbyquaker** [comment]
Sorry, hab Release 5.3.8 versemmelt, da steckt immer noch der Bug drin... 5.3.9 fixt ihn (hoffentlich final) ;-)

**Comment by Feldman01** [comment]
Ja funktioniert. Danke für die prompte Erledigung!

**Comment by sebastianmachon** [comment]
Hi zusammen,
ich habe leider das gleiche Problem in der Redmatic Version 5.5.3 😢 
Hatte es zeitweise wieder mit einem Downgrade auf 5.5.2 ans laufen bekommen, aber ab heute ging auch das irgendwie nicht mehr...

Habt ihr vielleicht einen Tipp für mich?
