### ISSUE TITLE
Homematic Kommunikationsprobleme IP Aktoren

### ISSUE THREAD

**Issue by GerdWilkening** [rdmtc/RedMatic-HomeKit#249]
Ich habe mit Redmatic folgendes Problem. Ich betreibe eine CCU3 mit Homematic und Homematic IP Aktoren. Auf der CCU habe ich folgende Addon's installiert: CuxDaemon und Readmatic. Firmware CCU3 und Addon's sind aktuell.
Mit installiertem Redmatic Addon kann ich keine Homematic IP Aktoren steuern (weder mit der HomeKit App noch mit der @Home 2.0 App und auch nicht über die WebUI der CCU), alle anderen Aktoren funktionieren.
Ich hatte gestern die CCU zu einem früheren Zeit (ohne Redmatic) zurückgesetzt und Redmatic neu installiert. Danach hat ed bis heute funktioniert. Seit dem habe ich die selben Fehler. Ich habe gesehen, dass heute eine neue Version zum Download zur Verfügung stand, mit einer Fehlerbehebung die zu meinem Problem passte. Dennoch funktioniert es immer noch nicht.
Können Sie mir helfen?

**Comment by hobbyquaker** [comment]
3-fach Post... :/ 
https://homematic-forum.de/forum/viewtopic.php?f=77&t=55789
https://github.com/rdmtc/RedMatic/issues/301
