### ISSUE TITLE
RedMatic stoppt immer wieder 

### ISSUE THREAD

**Issue by Andreas-78** [rdmtc/RedMatic-HomeKit#251]
Wenn homekit installiert wird stoppt die RedMatic immer wieder 

verändert wurde nichts nur ein update auf 5.3.9 gemacht muss man noch etwas anpassen oder ports frei geben?

**Comment by hobbyquaker** [comment]
Um zu sehen was da schief läuft brauche ich ein Log auf Debug Level: https://github.com/rdmtc/RedMatic/wiki/Loglevel

**Comment by Andreas-78** [comment]
Hallo 
danke für die Antwort,log schicke ich morgen bin noch unterwegs.
Hatte heute Vormittag noch mal versucht es  geht ab da schief wo man einen neuen Flow aufmacht und das HomeKit reinzieht.
Plötzlich geht die redmatic auf Stop
Und versucht sich dann ohne Erfolg ständig wieder zu verbinden 

Mit freundlichen Grüßen 
A.Klein

**Comment by Andreas-78** [comment]
Hallo,
hier mal das log .
Wobei ich noch hoffe das es nicht ein Problem mit der Fritzbox ist denn die ist nun auch schon ein paar mal abgeschmiert .
[redmatic.2020-01-19T10_19_44.834Z.log](https://github.com/rdmtc/RedMatic-HomeKit/files/4082502/redmatic.2020-01-19T10_19_44.834Z.log)

**Comment by hobbyquaker** [comment]
Ich glaube ich sehe die Ursache, habe wohl einen Bug beim `HB-UNI-Sen-TEMP-DS18B20`. Bis ich das gefixt habe könntest den als Workaround vorläufig deaktivieren.

**Comment by hobbyquaker** [comment]
@Andreas-78 Fehler sollte mit RedMatic 5.4.0 behoben sein. Bitte gib bescheid ob alles passt.

**Comment by Andreas-78** [comment]
Hallo
Ich konnte leider nicht so lange warten und habe alles komplett neu aufgesetzt.
Zur Zeit läuft alles stabil.
Vielen Dank
