### ISSUE TITLE
Tormatic Garagentoraktor zeigt nur den Status, lässt aber das Tor nicht steuern.

### ISSUE THREAD

**Issue by if-usernamenotavailable** [rdmtc/RedMatic-HomeKit#253]
Hallo,
es geht um den hmIP Aktor HmIP-MOD-TM für Novoferm Garagentore.
Ich hab ihn via CCU3 angebunden und möchte ihn nun mittels Redmatic in Homekit migrieren.
Vielleicht liegt das Problem darin, dass über Kanal 1 sowohl der Status als auch das Kommando gesetzt werden und deswegen das Redmatic Garagen-Node nicht funktioniert.  Oder hab ich was falsch eingestellt (ist durchaus denkbar)?
Besten Dank!

<img width="931" alt="Bildschirmfoto 2020-01-19 um 20 04 08" src="https://user-images.githubusercontent.com/60068324/72686636-190f7d00-3af7-11ea-83ac-720afa1572bb.png">

<img width="502" alt="Bildschirmfoto 2020-01-19 um 19 59 57" src="https://user-images.githubusercontent.com/60068324/72686585-a1d9e900-3af6-11ea-85b1-4f9b0991c498.png">

<img width="488" alt="Bildschirmfoto 2020-01-19 um 20 07 06" src="https://user-images.githubusercontent.com/60068324/72686658-54aa4700-3af7-11ea-9fdd-44d33e8f5e50.png">

**Comment by hobbyquaker** [comment]
Siehe #255
