### ISSUE TITLE
HmIP-MOD-TM einbinden

### ISSUE THREAD

**Issue by celk** [rdmtc/RedMatic-HomeKit#255]
Bitte die Garagensteuerung HmIP-MOD-TM in Homekit einbinden. Herzlichen Dank!

**Comment by celk** [comment]
Nachtrag: Ich habe die Node Garage gefunden und eingebunden. Allerdings funktioniert die Ansteuerung per Homekit trotzdem nicht. Bei der Einrichtung wird mir auch nur Kanal 2 des Aktors angeboten (das ist das Licht). Wenn ich händisch den Kanal 1 angebe, tut sich aber nichts

**Comment by hobbyquaker** [comment]
Ja, der Garagentor-Accessoryist für den MOD-TM nicht geeignet, das ist nur für die Ansteuerung wie HmIP-WRC oder Schaltaktoren ausgelegt. Ich rüste Support für den MOD-TM baldmöglichst nach.

**Comment by Mibra-de** [comment]
Bin hier bisher stiller Leser und habe mich erst jetzt angemeldet. Wollte Dir Hobbyquaker mein herzlichstes Dank für Deine mühen und die ganze Arbeit ausdrücken. Hab durch deine Posts und Arbeit mittlerweile schon einiges zum laufen bekommen.

Freue mich schon sehr auf die Implementierung des HmIP-MOD-TM dann ist mein erstes Setup fast komplett und ich kann alles mit Homekit steuern. Danke dafür.

**Comment by hobbyquaker** [comment]
@celk @Mibra-de Sollte mit RedMatic 5.4.0 funktionieren. Bitte gebt bescheid ob alles passt.

**Comment by Mibra-de** [comment]
Hallo hobbyquaker, bei mir läuft es wunderbar inkl. separater Lichtsteuerung und Status des Tors.
Die Lüftungsposition des Tors scheint nicht zu gehen aber ich glaube so etwas ist in Homekit nicht vorgesehen. 

Vielen Dank für deine Mühe

**Comment by celk** [comment]
Großartig, funktioniert einwandfrei! Herzlichen Dank!!
