### ISSUE TITLE
Implement HmIP-SCI

### ISSUE THREAD

**Issue by stefanfejfar** [rdmtc/RedMatic-HomeKit#256]
Vermisse die HmIP-SCI Kontaktschnittstelle. Falls mal Zeit sein sollte :-)
Herzlichen Dank für dieses großartige Projekt!

**Comment by lohns2020** [comment]
Habe Gerade verzweifelt versucht den HmIP-SCI einzubinden ;-D
Wäre schön, es wäre bald möglich.
Super Projekt. Weiter so. Danke.

**Comment by hobbyquaker** [comment]
@stefanfejfar @lohns2020 Sollte mit RedMatic 5.4.0 funktionieren. Bitte gebt bescheid ob alles passt.

**Comment by lohns2020** [comment]
Funktioniert perfekt. Danke

**Comment by stefanfejfar** [comment]
Funktioniert! Herzlichen Dank
