### ISSUE TITLE
HmIP-SWDO-PL wird nicht in homematic gelistet und nach Homekit übertragen

### ISSUE THREAD

**Issue by rst2601** [rdmtc/RedMatic-HomeKit#259]
Hallo,

sollte ich keinen Fehler gemacht haben, da ich den „HmIP-SWDO-PL“ nicht in Node Red sehen und nach Homekit übermitteln kann, bitte den Tür-/Fensterkontakt hinzufügen.

Vielen Dank
Gruß Ralf

**Comment by hobbyquaker** [comment]
@rst2601 Sollte mit RedMatic 5.4.0 funktionieren. Bitte gib bescheid ob alles passt.

**Comment by rst2601** [comment]
@hobbyquaker : Der Sensor ist jetzt in HomeKit, Danke! Batterie-Status wird auch korrekt übermittelt. Alles perfekt. Herzlichen Dank für diese super Schnittstelle!
