### ISSUE TITLE
Homekit Bridge - Behanghöhe invertieren führt zur falschen Homekit-Anzeige und -Aktivität

### ISSUE THREAD

**Issue by djiwondee** [rdmtc/RedMatic-HomeKit#262]
Hallo,

auf meiner CCU3 mit RedMatic und Homekit Bridged betreibe ich drei Rollladenaktoren (HmIP-BROLL). Zwei davon klassisch für Rollladen vor Fenstern und eine steuert die Markise. 

Bei der Markise gibt es ein Problem. Hier habe ich auf der CCU bei den Einstellungen die Behanghöhe hochgefahren invertiert:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/37173958/76512544-255bea80-6455-11ea-946d-0447a3368152.png">

Das macht ja Sinn, da im geschlossenen/eingefahrenen Zustand (=Markise vollständig aufgerollt = kein Sonnenschutz) der horizontaler Behang = 0% entspricht.

Scheinbar hat RedMatic-Homekit damit ein Problem. Der richtige Status in der Home.app wird nur nach dem Neustart der CCU RedMatic richtig angezeigt. Sobald man über die HomeApp interagiert (öffnen/schließen) geht es drunter und drüber:

Wenn die Markise ein kleines Stück geöffnet ist, zeigt die Home.app statt 6% eben das an:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/37173958/76513025-ef6b3600-6455-11ea-84b1-1ce852133e92.png">

Vollständiges Öffnen und Schließen dementsprechend.

Die Actor-Aktivität ist ebenso vertauscht:
<img width="145" alt="Bildschirmfoto 2020-03-12 um 11 39 41" src="https://user-images.githubusercontent.com/37173958/76513300-630d4300-6456-11ea-81a8-c7d3db2262a2.png">
Wir die Markise ausgerollt, wird "Schließen" angezeigt und wird die Markise eingerollt, wird "Öffnen" angezeigt.

Außerdem wird bei vollständig eingefahren (=alles aufgerollt)- oder vollständig ausgefahren (=alles abgerollt=100% Beschattung) der Status nur manchmal aktualisiert. 

Der Flow ist simple:

<img width="349" alt="Bildschirmfoto 2020-03-12 um 14 33 35" src="https://user-images.githubusercontent.com/37173958/76526899-8e039100-646e-11ea-9467-cf3c7aa6fa16.png">

Nur diese Kanäle habe ich in der HomeMatic Node ausgewählt:

<img width="501" alt="NR" src="https://user-images.githubusercontent.com/37173958/76526945-a07dca80-646e-11ea-9bd5-4b19eaa03119.png">

**Comment by djiwondee** [comment]
Habe mir im Moment anderweitig beholfen und lese die CCU-Kanäle zur Steuerung und Status für die [Homekit-Bridge](https://github.com/NRCHKB/node-red-contrib-homekit-bridged) über die CCU-Node-Red-Node aus:

<img width="1624" alt="image" src="https://user-images.githubusercontent.com/37173958/76685547-f4c2af00-6614-11ea-97d4-0c3f52b668b0.png">

Die Homematic node ist hier leider nicht zuverlässig genug. Interessant zu wissen wäre für mich, was die Kanäle so darstellen. Während ich die Steuer-Payloads für `LEVEL` an den Kanal 4 (`SHUTTER_VIRTUAL_RECEIVER`) schicke (z. B. `HmIP-BROLL 0xxxxxxxxxxx:4`), lese ich die Stati (`ACTIVITY_STATE` und `LEVEL`) jeweils im Kanal 3 (`SHUTTER_TRANSMITTER`z. B. `HmIP-BROLL 0xxxxxxxxxxx:3`) aus.

Der kleine Tweak mit der Delay-Node `Prevent parallel transmission` ist übrigens notwendig, da die beiden HmIP-BROLL-Taster direkt nebeneinander in der Wand verbaut sind. Die kommen sich wohl beim Funken in die Quere. Die CCU hat öfters mal _"Gerätekommunikation gestört"_ für einen oder beide der Aktoren angezeigt.

**Comment by djiwondee** [comment]
Zum eigentlichen [Problem](https://github.com/rdmtc/RedMatic-HomeKit/issues/262#issue-579852575) zurück. Das Ignorieren der Umkehrung der Behanghöhe scheint wohl seine Ursache innerhalb der CCU-Software zu haben. der Parameter hat wohl keinen Effekt. In meinem Flow
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/37173958/76706014-a2e95a00-66e4-11ea-8e99-ea171e81e589.png">
muss ich mir für den `LEVEL` auch das Komplement bilden. Der Node `Normalize level for current level` macht genau das
```
msg.payload = (1- msg.payload) * 100
return msg;
```
Dann passt auch die Anzeige in der Home.app 
<img width="110" alt="image" src="https://user-images.githubusercontent.com/37173958/76706337-03799680-66e7-11ea-80e0-5a739b704f1e.png">
obwohl das WebUI der CCU3 was anderes anzeigt:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/37173958/76706380-55bab780-66e7-11ea-8b0d-98f3bdde003f.png">
Auch Siri interpretiert die Parameter auf Kommandos wie `Markise schließen`, `Markise öffnen` etc.  richtig.
Stellt sich mir die Frage, mit der Einstellung der Behanghöhe in der CCU WebGUI: _"Works as designed, oder Bug?"_ Wäre das eine Issue bei eq-3 Support oder habe ich die Einstellung mit der Behanghöhe falsch verstanden. Weder im Homematic [IP-Anwenderhandbuch](https://www.eq-3.de/Downloads/eq3/download%20bereich/handbuecher/Homematic_IP-Anwenderhandbuch.pdf) noch im [WebUI-Handbuch](https://www.homematic-ip.com/downloads/download/handbuecher/WebUI_Handbuch_eQ-3.pdf) wird der Parameter erklärt :-(
Bin dankbar für jeden Tipp in der Richtung.

**Comment by djiwondee** [comment]
Habe diesbezüglich mal mit dem eq3-Support kontakt aufgenommen. 

> Der dort angegebene Parameter bezieht sich tatsächlich rein auf die Spannungszufuhr. Also was passieren soll wenn der Strom weg war und dann wieder eingeschaltet wird.

Also _works as designed_. Zumindest durch die Homekit-Bridge mit Normalisierung des Payload auf das Komplement erreich ich was ich will `Markise schließen` an Siri oder in der Home.app rollt die Markise dann auf.

Mache den Track dann zu.

**Comment by Nort3l** [comment]
Hallo Zusammen,

@djiwondee wie ist denn deine Erfahrung bisher mit deinem Workaround? 
Ich suche nach einer Lösung die Behanghöhe korrekt anzeigen zu lassen. Denn sowohl in NodeRed, als auch im ioBroker wird es über die Adapter zu Homekit falsch angezeigt.
Danke und viele Grüße, Dominik

**Comment by djiwondee** [comment]
@Nort3l 

wenn mit meinem Workaround [das hier](https://github.com/rdmtc/RedMatic-HomeKit/issues/262#issuecomment-599237856) gemeint ist, so funktioniert das zuverlässig über Apple Home.app und Siri. Ich benutze die CCU3 Web UI nicht für Interaktionen, sondern ausschließlich die Home.app und eben Siri.

Mittlerweile habe ich den Flow noch vereinfacht.
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/37173958/103478747-1883fb00-4dc9-11eb-8655-1349e262833b.png">
Damit funktioniert auch das Anzeigen der "Öffnen" und "Schließen"-Zustände während des Ein-/Ausfahrens der Markise besser.
```
[{"id":"226430cc.c473f8","type":"comment","z":"2d1f8eaf.e62472","name":"Terrace Awning","info":"","x":140,"y":540,"wires":[]},{"id":"ee1a6046.218bd8","type":"homekit-service","z":"2d1f8eaf.e62472","isParent":true,"bridge":"1899d266.8d864e","parentService":"","name":"Terrace Awning","serviceName":"WindowCovering","topic":"","filter":false,"manufacturer":"eQ-3","model":"HmIP-BROLL","serialNo":"00111A498EB386","firmwareRev":"","hardwareRev":"","softwareRev":"","cameraConfigVideoProcessor":"","cameraConfigSource":"","cameraConfigStillImageSource":"","cameraConfigMaxStreams":"","cameraConfigMaxWidth":"","cameraConfigMaxHeight":"","cameraConfigMaxFPS":"","cameraConfigMaxBitrate":"","cameraConfigVideoCodec":"","cameraConfigAudioCodec":"","cameraConfigAudio":false,"cameraConfigPacketSize":"","cameraConfigVerticalFlip":false,"cameraConfigHorizontalFlip":false,"cameraConfigMapVideo":"","cameraConfigMapAudio":"","cameraConfigVideoFilter":"","cameraConfigAdditionalCommandLine":"","cameraConfigDebug":false,"cameraConfigInterfaceName":"","characteristicProperties":"{    \"Name\": \"Terrace Awning\",    \"CurrentPosition\" :    {        \"minValue\":0,        \"maxValue\":100    },    \"TargetPosition\" :    {        \"minValue\":0,        \"maxValue\":100    },    \"PositionState\" :    {        \"validValues\": [0,1,2]    },    \"ObstructionDetected\" : false}","waitForSetupMsg":false,"outputs":2,"x":1100,"y":680,"wires":[["e882465.ecbd238"],["921d4bda.659138"]]},{"id":"dbe5477a.acdda","type":"function","z":"2d1f8eaf.e62472","name":"Set HkMsg","func":"var hkMsg = {};\n\nif (msg.payload.PositionState == 3){\n    // End positions or stopped\n    \n    hkMsg.payload = {\n        \"CurrentPosition\" : (1 - msg.payload.CurrentPosition) * 100,\n        \"TargetPosition\": (1 - msg.payload.CurrentPosition) * 100,\n        \"PositionState\": 2\n    }\n}\nelse if (msg.payload.PositionState == 2) {\n    // down\n    \n    hkMsg.payload = {\n        \"CurrentPosition\" : (1 - msg.payload.CurrentPosition) * 100,\n        \"TargetPosition\": 100,\n        \"PositionState\": 1\n    }\n}\nelse if (msg.payload.PositionState == 1) {\n    // up\n    \n    hkMsg.payload = {\n        \"CurrentPosition\" : (1 - msg.payload.CurrentPosition) * 100,\n        \"TargetPosition\": 0,\n        \"PositionState\": 0\n    }\n}\n\n\nreturn hkMsg;\n\n","outputs":1,"noerr":0,"initialize":"","finalize":"","x":830,"y":680,"wires":[["639012ea.04a8c4","ee1a6046.218bd8"]]},{"id":"7ad15020.08eea8","type":"function","z":"2d1f8eaf.e62472","name":"Persist current level","func":"flow.set(\"currentLevelTerraceAwning\", (1 - msg.payload) * 100);\n\nreturn msg;\n","outputs":1,"noerr":0,"x":570,"y":620,"wires":[[]]},{"id":"b8dcb7a8.c66638","type":"ccu-value","z":"2d1f8eaf.e62472","name":"HkMsg to RedMatic ","iface":"HmIP-RF","channel":"00111A498EB386:4 HmIP-BROLL 00111A498EB386:4","datapoint":"LEVEL","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":1420,"y":920,"wires":[[]]},{"id":"e882465.ecbd238","type":"switch","z":"2d1f8eaf.e62472","name":"Check hap.context","property":"hap.context","propertyType":"msg","rules":[{"t":"nnull"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":1410,"y":680,"wires":[["a3d7090a.3d9858"],[]],"info":"make sure only Home.app initaited messages gets passed through"},{"id":"a0fecade.9bf828","type":"function","z":"2d1f8eaf.e62472","name":"Normalize Level for RedMatic ","func":"msg.payload = 1 - msg.payload / 100;\nreturn msg;","outputs":1,"noerr":0,"x":1450,"y":860,"wires":[["b8dcb7a8.c66638"]]},{"id":"a3d7090a.3d9858","type":"switch","z":"2d1f8eaf.e62472","name":"Check TargetPosition","property":"payload.TargetPosition","propertyType":"msg","rules":[{"t":"nnull"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":1420,"y":740,"wires":[["82d6f7b5.464e68"],[]]},{"id":"82d6f7b5.464e68","type":"change","z":"2d1f8eaf.e62472","name":"Move Msg RedMatic","rules":[{"t":"move","p":"payload.TargetPosition","pt":"msg","to":"payload","tot":"msg"},{"t":"delete","p":"payload.TargetPosition","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1420,"y":800,"wires":[["a0fecade.9bf828"]]},{"id":"427d28d9.632ed8","type":"ccu-rpc-event","z":"2d1f8eaf.e62472","name":"Terrace Awning Current Position","iface":"HmIP-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"Taster","functionsRx":"str","device":"00111A498EB386","deviceRx":"str","deviceName":"Wohnzimmer Terrasse Markise","deviceNameRx":"str","deviceType":"HmIP-BROLL","deviceTypeRx":"str","channel":"00111A498EB386:3","channelRx":"str","channelName":"HmIP-BROLL 00111A498EB386:3","channelNameRx":"str","channelType":"SHUTTER_TRANSMITTER","channelTypeRx":"str","channelIndex":"","channelIndexRx":"str","datapoint":"LEVEL","datapointRx":"str","change":false,"working":false,"cache":true,"topic":"CurrentPosition","x":230,"y":620,"wires":[["7ad15020.08eea8","a4531957.4fbfe"]]},{"id":"918e2752.4eec38","type":"ccu-value","z":"2d1f8eaf.e62472","name":"Terrace Awning PositionState","iface":"HmIP-RF","channel":"00111A498EB386:4 HmIP-BROLL 00111A498EB386:4","datapoint":"ACTIVITY_STATE","mode":"","start":true,"change":false,"cache":true,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"PositionState","x":220,"y":680,"wires":[["a4531957.4fbfe"]]},{"id":"a4531957.4fbfe","type":"join","z":"2d1f8eaf.e62472","name":"","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"topic","joiner":"\\n","joinerType":"str","accumulate":true,"timeout":"","count":"1","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"","reduceFixup":"","x":530,"y":680,"wires":[["dbe5477a.acdda"]]},{"id":"639012ea.04a8c4","type":"debug","z":"2d1f8eaf.e62472","name":"","active":false,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","x":970,"y":800,"wires":[]},{"id":"921d4bda.659138","type":"mqtt out","z":"2d1f8eaf.e62472","name":"","topic":"hk/status/Livingroom/Switch/TerraceAwning","qos":"1","retain":"false","broker":"107097e2.fc9c48","x":1490,"y":980,"wires":[]},{"id":"1899d266.8d864e","type":"homekit-bridge","bridgeName":"NRCHKB-03-PROD","pinCode":"003-03-003","port":"","allowInsecureRequest":false,"manufacturer":"eQ-3","model":"CCU3","serialNo":"000000008c02b30a","firmwareRev":"","hardwareRev":"BCM2835","softwareRev":"a02082","customMdnsConfig":false,"mdnsMulticast":true,"mdnsInterface":"","mdnsPort":"","mdnsIp":"","mdnsTtl":"","mdnsLoopback":true,"mdnsReuseAddr":true,"allowMessagePassthrough":true},{"id":"38263145.35ea0e","type":"ccu-connection","name":"CCU local","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":false,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":"default"},{"id":"107097e2.fc9c48","type":"mqtt-broker","name":"Mosquitto-raspi-smarthome","broker":"raspi-smarthome","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":"","closeTopic":"","closeQos":"0","closeRetain":"false","closePayload":"","willTopic":"","willQos":"0","willRetain":"false","willPayload":""}]
```
Vielleicht noch mal wichtig zu erwähnen, dass ich nicht das [Redmatic-Homekit-Plugin](https://github.com/rdmtc/RedMatic-HomeKit) nutze, um meine CCU3 gekoppelten HmIP-Geräte in Apple Homekit einzubinden, sondern [das hier](https://github.com/NRCHKB/node-red-contrib-homekit-bridged). Von einem Parallel-Betrieb dieser node-red-contribs auf der CCU3 mit Redmatic rate ich dringend ab. Da kommen sich die Ports in die Quere!

**Comment by Nort3l** [comment]
Danke Dir für die Rückmeldung. Jetzt müsste ich den Flow nur noch nachbauen können.
Das wäre dann die nächste Herausforderung.
