### ISSUE TITLE
HmIPW-DRS8 - Ausgänge nicht separaten Räumen zuzuordnen

### ISSUE THREAD

**Issue by son1x** [rdmtc/RedMatic-HomeKit#269]
RedMatic Version: 5.5.2 / 5.5.3 (beide)
CCU3 Version: 3.51.6

Ähnlich wie in #242 kommt es zu folgendem Problem:

Die Schaltausgänge werden zwar in HomeKit angezeigt, auch lässt sich das Gerät in die 8 einzelnen Ausgänge aufteilen, aber:

Die Schaltausgänge lassen sich nur dem selben Raum zuordnen.
Wenn ein Schaltausgang auf einen anderen Raum gelegt wird, ziehen alle anderen Geräte ebenfalls den neuen Raum.

**Comment by euskij** [comment]
Habe dasselbe problem. Bei mir liegen mehrere Schalter auf einem Aktor. Der Aktor wird in HomeKit als ein Gerät angezeigt mit 8 Schaltern. Sobald man die Schalter auflöst und einem anderen Raum zuordnet, verschieben sich alle anderen Schalter direkt mit.

**Comment by euskij** [comment]
Lässt sich lösen indem man bei der Konfiguration der Bridge in Redmatic unter dem Aktor das Häckchen "SingleAccessory" rausnimmt. Danach ist jeder Schalter einzeln in Homekit verfügbar.
