### ISSUE TITLE
[Done] HM-LC-SW4-DR hinzufügen

### ISSUE THREAD

**Issue by fischmir** [rdmtc/RedMatic-HomeKit#271]
Hallo @hobbyquaker ,

danke für die hervorragende Arbeit.

Ich habe nun alle Geräte in der Home-App in Räume organisiert. Übrig geblieben ist der HM-LC-SW4-DR. Hier werden mir nicht die Namen der Kanäle angezeigt.

Kann das vielleicht hinzugefügt werden?

Danke und Grüße
Christian

**Comment by fischmir** [comment]
Hallo @hobbyquaker,

ist das Projekt gestorben? Wenn ich mir die offenen Issues anschaue, dann könnte dem fast so sein.

Danke für eine kurze Rückmeldung.

Danke und Grüße
Christian

**Comment by fischmir** [comment]
Nach einigen Stunden habe ich es geschafft. Es lag wahrscheinlich am / im Namen, dass der Kanalname nicht in Homekit angezeigt wurde.

Done.

**Comment by hobbyquaker** [comment]
Klar lebt es noch :) Hab nur keine Zeit gefunden...
