### ISSUE TITLE
Probleme mit Homebridge Version 1.0.04

### ISSUE THREAD

**Issue by Donni1966** [rdmtc/RedMatic-HomeKit#275]
Hi, 

ich habe versucht auf die Version Homebridge 1.0.04 hoch zu rüsten und neben den zig Plugins muss auch Red-Matic HomeKit aktualisiert werden? 

wenn ich das Update mache habe ich mim Config keine gerate mehr, die zugeordneten geht noch, aber lassen sich nicht mehr ändern ( Liste leer) und wenn ich dann ( dachte ne gute Idee) den RedMatic neustarte stürzt sie nach ein par Sekunden ab und starten durch in der Dauerschleife. 

ich bin wieder runter auf die x.53 und alles geht wieder.

**Comment by hobbyquaker** [comment]
Ich glaube Du missverstehst da was. RedMatic-HomeKit hat nichts mit Homebridge zu tun (abgesehn davon dass sie beide auf HAP-Nodejs basieren sind es).

**Comment by Donni1966** [comment]
Hi. 
Ist mir schon klar. Aber seit Redmdtic ein Update bekam damals im Mai geht es ...
