### ISSUE TITLE
HomeKit Kamera geht nur im wlan

### ISSUE THREAD

**Issue by hannoverRed** [rdmtc/RedMatic-HomeKit#277]
hi,

ich habe es geschafft die homeKit Cam einzurichten und sie funktioniert auch.
Allerdings NUR im WLAN! im UMTS netzt funktioniert sie nicht mehr!
ich bräuchte da mal bitte Hilfe.
lg aus Hannover

**Comment by hobbyquaker** [comment]
Hast Du eine HomeKit Zentrale (Apple TV, HomePod, ...)?

**Comment by hannoverRed** [comment]
Einen Apple TV 

Mit freundlichem Gruß

Jörn Völkening
Podbielskistraße 282
30655 Hannover
Germany

Mobiltelefon: +49 (0) 1567 8515797
eMail: j.voelkening@icloud.com

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Falls Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben,
informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender
immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.
