### ISSUE TITLE
Homekit Node partly connected

### ISSUE THREAD

**Issue by guenter-ms** [rdmtc/RedMatic-HomeKit#287]
Hello, 
the HomeKit Node shows a state of "partly connected" after some hours or days of "connected".
How can I find out the reason?
Thanks Guenter

**Comment by hobbyquaker** [comment]
Set the log level of Node-RED to "debug" (see https://github.com/rdmtc/RedMatic/wiki/Loglevel) and try to find some log message from the Node `ccu-connection` that includes the term `disconnect`. Or just upload a log here and I'll take a look.

**Comment by guenter-ms** [comment]
Its stable for the time being. Maybe after upgrading all components. Can be closed at this time. Thank you
