### ISSUE TITLE
Topic in Event Node

### ISSUE THREAD

**Issue by Ataraxiall** [rdmtc/RedMatic-HomeKit#289]
Good morning!

I am trying to use the event node but it tells me that the topic is wrong Where could you see how to send data to it?

Thanks and best regards!

**Comment by hobbyquaker** [comment]
Some german documentation of the event node can be found here: https://github.com/rdmtc/RedMatic/wiki/Homekit#tasten
Basically it expects the topic to consist of the Button number (starting at 1) and PRESS_SHORT or PRESS_LONG, e.g. `1/PRESS_SHORT`.
