### ISSUE TITLE
Türklingel Node für den HomePod

### ISSUE THREAD

**Issue by Hoefti1980** [rdmtc/RedMatic-HomeKit#293]
Hallo,
bei der HomePod Software 14.1 ist es jetzt möglich einzustellen das ausgewählte HomePods Klingeln wenn die Klingel betätigt wird.
Jetzt ist mein Problem das ich keine HomeKit fähige Klingel nutzte, sondern einen Taster Eingang von meinem Homematic Wired RS485 Modul.
Ist es möglich einen Doorbell Taster zu erzeugen der funktioniert? Er müsste ja dann als Klingel in der App erkannt werden.
Mit dem Universal Node funktioniert es leider nicht :-(. 

Gruß 
Hoefti

**Comment by Hoefti1980** [comment]
Ich habe es jetzt mit dem Kamera Node hinbekommen, auch ohne Kamera.
Der HomePod klingelt sofort nach dem Tastendruck, läuft wirklich super.

Gruß
Hoefti

**Comment by julembke** [comment]
wie kann mann einen Homematic Kontakt als Klingeltaster in der Kamera Node konfigurieren ?
