### ISSUE TITLE
RedMatic Node-red Aktuallisiert keine Zigbee Geräte

### ISSUE THREAD

**Issue by FuellSv** [rdmtc/RedMatic-HomeKit#300]
Hallo,

vielleicht könnt ihr mir helfen, ich habe auf meiner CCU3 (RaspberryMatic) Red-Matic Installiert und dann im Node-Red das Zusatz Paket Homekit, hier hat auch alles geklappt... jetzt habe ich die CCU3 mit einem Osram Gateway gekoppelt und 4 Steckdosen an das Gateway angelernt. Diese werden auch in der CCU angezeigt aber nicht im Homekit adapter... 
Ich habe alle Systeme ein paar mal schon Neugestartet und auch im Node-Red alles aktualisiert

**Comment by hobbyquaker** [comment]
Die CCU-eigene Integration von Hue/Osram werden von RedMatic nicht unterstützt, von meiner Seite besteht da auch nicht wirklich Interesse... Alternativen für Dich könnte sein: Eine Philips Hue Bridge und node-red-contrib-hue-magic nutzen, Deconz und node-red-contrib-deconz nutzen oder Zigbee direkt einbinden via node-red-contrib-zigbee.
