### ISSUE TITLE
HM-ES-TX-WM -> Connection Lost

### ISSUE THREAD

**Issue by Iceman1101** [rdmtc/RedMatic-HomeKit#306]
Hi,
I am trying to build my own S0 Adapter and compare it right now with the original HM-ES-TX-WM with an LED Sensor (Adapter to S0).
I actually Simulate the S0 Contact with an ATTiny and have the original HM-ES-TX-WM in Parallel with your HM-ES-TX-WM what I can download in your Librery.

The Probelm I face it that I loose the connection to the board caused by the Sleep Mode.
I have an Arduino328 with and without external click. Both have the same issue.
What do I need to change in the Script if I want to use the SleepRTC?
It is a Script Problem, help would be prevented.

The Original HM-ES-TX-WM is actually doing fine while I keep loosing the connection to my Arduino.

Antenne Connection of the Arduino is better, 66db against 90db of the original.

Do we know about such a Problem and can I fix it in the Arduino Skript?

I would really need your support in this Issue, Thanks

**Comment by Iceman1101** [comment]
BTW, the total Power is actually the same when Transmitted and it is getting really bad when I try to simulate more than 3000W.
Possibly that your skript try to send more than the adjustet 3 min? Or does it get disturbed by the pulsing?
Antenna Load is quite normal, so I am struggeling to find the Problem

**Comment by Iceman1101** [comment]
Looks like Problem with the Sleepmode, any hints?

**Comment by hobbyquaker** [comment]
I think you're in the wrong issue tracker.
