### ISSUE TITLE
Redmatic / Komponente der Zentrale stürzt ab - Homekit

### ISSUE THREAD

**Issue by RealWinny** [rdmtc/RedMatic-HomeKit#307]
Hallo, ich bin gerade dabei mir mit Redmatic Homekit und HomeMatic zu verbinden. Verwendet habe ich dabei diese Anleitung: [YouTube](https://www.youtube.com/watch?v=2I3UlTJ3ar8)

Leider habe auch wie (wie scheinbar öfters auch andere) Probleme mit Abstürzen. Ich habe schon viel gegoogelt, kann aber mein Problem nicht identifizieren.

Ohne dass ich jetzt wirklich einen Grund erkennen kann, stürzt laut CCU-Meldung "eine Komponente der Zentrale" ab, sobald ich etwas in NodeRed einstelle. Mal sofort, mal dauert es länger. Zuletzt bin ich zumindest schon bis zum QR-Code gekommen, dann war aber wieder Schluss. 

Anbei hängt die Log-Datei der CCU. Hat jemand eine Idee, was ich falsch mache?

Vielen Dank für die Hilfe!

[CCU3-2020-11-15.log](https://github.com/rdmtc/RedMatic-HomeKit/files/5542228/CCU3-2020-11-15.log)

**Comment by RealWinny** [comment]
Hallo @hobbyquaker, könntest du hier vielleicht einen Blick drauf werfen? Ich komme leider nicht weiter.

**Comment by hobbyquaker** [comment]
In dem Log ist leider kein Node-RED Absturz zu sehen, falls das Problem noch besteht bitte noch mal ein Log erzeugen wie hier beschrieben: https://github.com/rdmtc/RedMatic/wiki/Loglevel

**Comment by RealWinny** [comment]
Leider nicht mehr. Habe eine andere Lösung gefunden.
