### ISSUE TITLE
HomeMatic 4fach Schaltaktor

### ISSUE THREAD

**Issue by hannoverRed** [rdmtc/RedMatic-HomeKit#314]
Hallo zusammen,

Ich habe bei mir mehrere 4 fach Hutschienen Aktoren verbaut.
Beispiel wie auf dem Foto: sind bei einem Aktor Lichter aus verschieden Räumen angeschlossen.
Jetzt habe ich das Problem das ich auch wenn ich in HomeKit mir den Aktor als Separate Felder anzeigen lasse, diese nicht den jeweiligen einzelnen Räume zuordnen kann.
Es werden jedes Mal alle 4 Geräte in den neuen Raum verschoben.
Kann mir da jemand weiter helfen?
Würde ungern an der Verteilung die Verkabelung neu machen.
Lg![image](https://user-images.githubusercontent.com/60238337/103151108-6a9aa000-477b-11eb-8c3f-cb55e09c98b1.png)
![image](https://user-images.githubusercontent.com/60238337/103151110-6f5f5400-477b-11eb-9119-3c9deeca0f45.png)

**Comment by mdoster-de** [comment]
Ich habe dafür pro (Teil-)Aktor, der ein Geräte, der in einem anderen Raum steuert, eine weitere Bridge angelegt, die nur den betreffenden (Teil-)Aktor als Gerät enthält und in der ursprünglichen Bridge muss der Aktor natürlich abgehakt werden. So können die Geräte wieder einem Raum zugeordnet werden.

**Comment by hobbyquaker** [comment]
@hannoverRed konnte das deaktivieren von "SingleAccessory" Dein Problem lösen?

**Comment by hannoverRed** [comment]
@hobbyquaker Nein das hat leider keine Änderung gebracht.
Muss ich nachdem ich den Hacken entfernt habe noch die Geräte in der Home App neu laden oder so?
Die Geräte werden mit oder ohne hacken Ja einzeln angezeigt. Nur das wenn ich eines von dem 4er schaltaktor in einem anderen Raum schiebe die anderen 3 halt auch wechseln
