### ISSUE TITLE
HomeMatic WTH werden nicht angezeigt

### ISSUE THREAD

**Issue by Feddero** [rdmtc/RedMatic-HomeKit#316]
Guten Tag,

ich bin relativ neu in RedMatic und habe eine Frage zu den Geräten, die mir in HomeKit angezeigt werden.

Ich habe in meiner HomeMatic-Wired-Installation insgesamt 9 WTH (Wandthermostate) und zwei Heizkreisverteiler.
Die Wandthermostate und der Heizkreisverteiler werden mir leider nicht in RedMatic und auch nicht in HomeKit angezeigt, hatte das Problem schon mal jemand oder kann mir jemand sagen, was ich tun muss, um die Geräte zu integrieren?
Alle WIRED-Eingangs, Ausgangs und Rolladen-Module werden mir korrekt angezeigt.

In der WEBUI kann ich die WTH-Geräte sehen und auch bedienen.

Vielen Dank!

Gruß Daniel

**Comment by Feddero** [comment]
Ich habe gerade eine Liste von unterstützten Homematic-Produkten gefunden und leider meine HMIPW-WTH nicht gefunden.
Werden die irgendwann noch eingepflegt oder funktioniert das nicht?

Vielen Dank!

**Comment by hobbyquaker** [comment]
Duplicate #313
