### ISSUE TITLE
Akku Status in Universal Acc schreiben

### ISSUE THREAD

**Issue by Donni1966** [rdmtc/RedMatic-HomeKit#318]
Hi und ich hoffe mir kann einer helfen. 
Ich will mir ein Homekit basteln, was den Status meines -Autos darstellt.
Also: 
- Fenster offen? -> Windows
- Türen offen -> Doors oder Contact
- Laden ja nein -> Contact Sensor
- Eingesteckt ja nein - Contact
- Akku -> BatteryService
- Reichweite -> ? 

Ich kann die Laden und Eingesteckt schon sehen. Was ich nicht hinbekomme, weil ich irgendwie nicht verstehe, wie ich das machen kann ist der Akku status. 

ich wollte das mit einer Funktion machen 
msg = {
  "topic": "2/BatteryService",
  "payload": {"BatteryLevel":80, "ChargingState":1, "StatusLowBattery":0, "Name": "Akku"}
}
return msg

2 - ist der dritte in der Liste des Homekit Gerätes - Typ : 
BatteryService

Wahrscheinlich mache ich einen Denkfehler ... vielleicht hat einer einen Tip für mich? 

byby, Michael

**Comment by Jemeins** [comment]
Moin,
versuch mal den BatteryService in Kombination mit einem Kontaktsensor zu nutzen.
Soweit ich weiß gibt es in HomeKit leider keinen alleinstehenden BatteryService.

**Comment by Donni1966** [comment]
> BatteryService in Kombination mit einem Kontaktsensor zu nutzen.
@Jemeins 
ja ich habe mich für einen Bewegungssensor entschieden. Danke für den Tipp. 

Ich nutzte nun die Daten "Angesteckt" als Bewegung, Ladesstatus als Batterie wird geladen und den Status für den Akkustand des Autos. 

jetzt bastel ich mal an den anderen Sachen rum 

![screenshot](https://user-images.githubusercontent.com/61660957/104000311-5b194f00-519e-11eb-8022-e1ba71731713.png)
