### ISSUE TITLE
Unterstützung für HmIP-DRSI1

### ISSUE THREAD

**Issue by itshappyli** [rdmtc/RedMatic-HomeKit#320]
Hallo zusammen!

Erstmal vorweg ein großes Danke für dieses großartige Projekt!

Gibt es Pläne auch den DRSI1 in das RedMatic-HomeKit Programm aufzunehmen?  Der große Bruder DRSI4 scheint schon diesbezüglich implementiert zu sein. Wäre total schön, wenn man dies bei Gelegenheit auch für den DRSI1 implementieren könnte.

Danke und schöne Grüße!

**Comment by julembke** [comment]
Ich sehe den Schalter jetzt in HomeKit

**Comment by itshappyli** [comment]
Hi, vielen Dank für die Implementierung! Ist jetzt in HK sichtbar und funktioniert tadellos!

Danke danke danke!!!
