### ISSUE TITLE
CurrentTemperature

### ISSUE THREAD

**Issue by rauchmandl** [rdmtc/RedMatic-HomeKit#323]
Guten Morgen, 

Ich versuche jetzt schon einige Zeit die Temperatur eines Aussentemperaturfühlers in homekit zu bringen.
Funktioniert eigentlich auch einwandfrei. aber sobald der Wert ins Minus geht, zeigt mir die home app nur mehr 0.0 an.
Auch mit dem InjectNode kann ich nur positive Temperaturen auslösen. Sobald ich ein Minus voransetze wieder 0.0.
Es ist dabei egal was ich für einen Sensor nehme, auch beim Thermostat zeigt er kein Minus.
Kann mir irgendwer sagen was ich falsch mache?

LG Josef

**Comment by rauchmandl** [comment]
Weiters ist mir beim Testen aufgefallen, das Temperaturen zwischen 0 und 100 in 0,5 Grad Schritten funktionieren! Nichts darüber hinaus, nichts darunter! LG aus der Südweststeiermark, Josef

**Comment by Jemeins** [comment]
Guten Abend,
Eine wirklich sehr hilfreiche Seite: https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts

/**
 * Characteristic "Current Temperature"
 */

export class CurrentTemperature extends Characteristic {

  static readonly UUID: string = '00000011-0000-1000-8000-0026BB765291';

  constructor() {
    super('Current Temperature', CurrentTemperature.UUID);
    this.setProps({
      format: Formats.FLOAT,
      unit: Units.CELSIUS,
      **maxValue: 100,**
      **minValue: 0,**
      minStep: 0.1,
      perms: [Perms.READ, Perms.NOTIFY]
    });
    this.value = this.getDefaultValue();
  }
}

Characteristic.CurrentTemperature = CurrentTemperature;

Ich vermute negative Temperaturen werden nicht unterstützt.

Mit freundlichen Grüßen

**Comment by rauchmandl** [comment]
Guten Abend! Danke für den Link!  Bin von folgender Anleitung ausgegangen: https://auto.caitken.com/posts/2018/09/09/nodered-homekit-characteristics-reference#CharCurrentTemperature

Und mit den homematic sensoren über den entsprechenden node wird Minus ja auch angezeigt! 

LG Josef

**Comment by rauchmandl** [comment]
Hab gerade in der Apple HomeKit Accessory Protocol Specification nachgesehen, da steht auch 0 - 100! Wie hat @hobbyquaker das mit den homematic Sensoren geschafft? LG Josef

**Comment by Jemeins** [comment]
Ich denke hier wird ganz gut beschrieben wie du die Eigenschaften ändern kannst:
https://github.com/rdmtc/RedMatic-HomeKit/issues/111
Auf CurrentTemperature anpassen, Neustarten und dann sollte es gehen

**Comment by rauchmandl** [comment]
Das hört sich doch gut an! Vielen Dank, das versuch ich und melde den Erfolg! Danke einstweilen, lg Josef

**Comment by rauchmandl** [comment]
Das hat einwandfrei funktioniert! Es war nur ein Neustart von NodeRed notwendig bevor es funktioniert hat!   Vielen, vielen lieben Dank! LG Josef
